### ISSUE TITLE
Auto load of next pages

### ISSUE THREAD

**Issue by FelixPetriconi** [ZachSaucier/Just-Read#102]
Several websites have separated their content into several pages that must be access through individual links or through a select buttons.

It would be fantastic, if this great tool could check if there are next pages and loads them automatically. (E.g. the Mercury Reader extension can do this, but this plugin has a better text layout.)

**Comment by ZachSaucier** [comment]
This seems like a tough task, requiring Just Read to change a few different things to get it working. I likely won't get around to it for a while due to lack of time, but I'll eventually try some things out to try and get it working, at least for common sites where this is the case. 

Do you have any example sites where this happens?

Thanks for the suggestion.

**Comment by FelixPetriconi** [comment]
I don't know English spoken pages at hand, but this is a German one: http://www.faz.net/aktuell/politik/ausland/drei-tage-gefangenschaft-in-kongo-freiwillig-will-ich-meinen-sarg-nicht-besteigen-1582792.html?GEPC=s3

**Comment by ZachSaucier** [comment]
This is out of scope for Just Read given the extremely wide variety of ways that this sort of functionality can be implemented.
