### ISSUE TITLE
The banner image does not appear in Just Read

### ISSUE THREAD

**Issue by fortunate-man** [ZachSaucier/Just-Read#104]
For example, [in this Wired article](https://www.wired.com/story/forget-the-driverless-future-get-ready-to-physically-merge-with-a-car?mbid=nl_091417_daily&CNDID=%%CUST_ID%%), the first image (the blue car), does not appear in the read mode. I've been seeing this in many of the Wired articles I visit.

**Comment by ZachSaucier** [comment]
Thanks for the report! This is because the banner image is actually outside of the article, so Just Read has a hard time knowing that it's relevant. I'll think about how to restructure JR to find images like this, but I can't promise a fix soon. 

For now you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) if getting the banner image is really important to you.

I also edited your post to make it more general so this issue can be a catch all for similar sites.

**Comment by Fortunate-MAN** [comment]
ok, thank you! Nothing to hurry upon, I just noticed this so I thought I'll make this issue.

**Comment by dodgyb** [comment]
Similar issue - the extension is not displaying the first paragraph of this [page](http://www.cmegroup.com/education/featured-reports/evolving-economics-of-bitcoin-gold-currencies.html)

I have noticed this on a couple of other sites too. See example output:

![capture](https://user-images.githubusercontent.com/1958461/32277471-76d9f962-bf0a-11e7-8577-66a5f52ba63f.PNG)

**Comment by ZachSaucier** [comment]
Given this functionality can be worked around using user selection mode as mentioned above, given on a site-by-site basis through Just Read Premium's [domain-specific selectors](https://github.com/ZachSaucier/Just-Read#q-can-i-customize-which-selectors-just-read-uses-for-selecting-the-date-author-title-header-image-and-content), and fixing this bug would require Just Read's methodology to change a good bit, this is a won't-fix for now unless someone can come up with a way to do this well.
