### ISSUE TITLE
Sidebar generated instead of article

### ISSUE THREAD

**Issue by jt618** [ZachSaucier/Just-Read#119]
When using just-read to view http://personalgrowthmap.com/blog/2009/03/20/understanding-the-seven-life-areas/ the sidebar is the only content viewable rather than the actual article.

**Comment by ZachSaucier** [comment]
This is caused because a comment on the page has a longer paragraph than any in the actual article. JR hides the comments as it's supposed to, but fails by selecting it instead of removing it from the selection process (because it classifies the comment using IDs instead of classes... which is very dumb on their part).

I've updated to check IDs during auto-selection against the blacklist to fix this issue in version 1.1.3 rolling out soon.
