### ISSUE TITLE
Article content about advertising doesn't show up at all

### ISSUE THREAD

**Issue by orschiro** [ZachSaucier/Just-Read#12]
Dear @ZachSaucier,

This site is broken:

http://blog.adstage.io/2015/04/13/understanding-audience-expansion-with-linkedin-ads/

![image](https://cloud.githubusercontent.com/assets/170947/19106334/0df889d4-8ae7-11e6-96f2-14b4c9c8777a.png)

**Comment by ZachSaucier** [comment]
Well, this is a rare edge case, haha. 

So, part of the default CSS file attempts to hide ads that are still within the content. It does this by detecting common CSS classes with things like "ads" or "advertisement" in it.

Since this article you link is *about* advertising, they have a class named `.tag-linkedin-ads` on the container for the main content (the same one Just Read selects) which makes it get hidden in Just Read's view.

I can't really think of a good way to work around this edge case without removing the functionality of hiding ads through CSS. I'm open to ideas though!

**Comment by lutc** [comment]
Hi man. Do you need links to sites with bugs? Or You have no time to develop this plugin?
[Link for example](http://bikepost.ru/blog/69642/Kratko-o-Honda-VTR1000-posle-prodazhi-i-bez-kupjur.html)

**Comment by ZachSaucier** [comment]
@lutc Thanks for the report! The issue for that site is for a completely different issue, one I've seen before, so I made a separate issue for it: #27

**Comment by ZachSaucier** [comment]
This should be fixed in Just Read version 1.0.24, as per #59
