### ISSUE TITLE
ToS generated instead of article content

### ISSUE THREAD

**Issue by jt618** [ZachSaucier/Just-Read#120]
The Terms of Service is generated instead of the article content. This occurs in the current version of both Chrome and IE when viewing website: https://blog.sivanaspirit.com/mf-gn-world-needs-empaths/?utm_campaign=Blog+-+11%2F25%2F17++%28QKRRku%29&utm_medium=email&_ke=amlsLnRhcnZlc0BnbWFpbC5jb20%3D&utm_source=Retail+Track+B+-+2xWeek+%28Less+Engaged%3B+Opened+or+Clicked+between+45+%26+120+days+ago%29

**Comment by ZachSaucier** [comment]
Thanks for the report! For now you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the article content on problematic pages like this.

P.S. Are you using JustRead in IE? If so, how? haha.

**Comment by ZachSaucier** [comment]
This is because the ToS had at least 2/5ths of the words on the page and the longest paragraph in it, haha. While I didn't fix *all* ToSs from being auto-selected generally, I made it so that Just Read does not select or show any elements that are visually hidden on the page when Just Read is initiated. As such, it fixes the error in the linked page. The change should be live in version 1.1.3, rolling out soon.
