### ISSUE TITLE
Improve table styling

### ISSUE THREAD

**Issue by Mohithjux** [ZachSaucier/Just-Read#121]
Hi Team,

The following wepage has the table , which is not veiwed correctly in the Just-Read Mode.
is it possible to fix it?
http://accounting-simplified.com/trial-balance.html

Screen Shot:
[Original]
![image](https://user-images.githubusercontent.com/34088207/33363335-4f06451a-d523-11e7-939b-4e4ed619d312.png)
[Just-Read Mode]
![image](https://user-images.githubusercontent.com/34088207/33363295-2853aaa2-d523-11e7-8adc-e4bd4b6735b4.png)

**Comment by ZachSaucier** [comment]
Thanks for the contribution! 

What exactly are you expecting the table to look like in the Just Read view? The exact same as the non-Just Read version? 

This is the intended behavior of Just Read because it aims to remove all formatting that the original page added. But you can customize the way your tables look using some CSS in the Just Read view.

**Comment by Mohithjux** [comment]
thanks for the reply.
I personally feel if just read can give the black color borders for the table, it will increase the readability.

**Comment by ZachSaucier** [comment]
That's a reasonable request. I think it makes sense for most tables and will help with readability, so I'll change the default stylesheet to include `td { border: 1px solid black; }` in the next update.

Thanks for the contribution!

**Comment by Mohithjux** [comment]
Thanks for considering, looking forward to the next update.

**Comment by ZachSaucier** [comment]
This change should be live as of version 1.1.3, which should be rolling out soon.
