### ISSUE TITLE
Problem with rendering of <fieldset> HTML tag

### ISSUE THREAD

**Issue by Rudoslav** [ZachSaucier/Just-Read#122]
Hi there,

I have a problem with rendering of **fieldset** tags when using Just-Read for chrome. The problem is, **elements inside** the **fieldset** tag are not being rendered,

Chrome version: Version 62.0.3202.75 (Official Build) (64-bit)
OS: Ubuntu 16.04.

I have encountered

http://alanstorm.com/magento_2_mvvm_mvc/

What it looks like when browsing **without** Just-Read:

![image](https://user-images.githubusercontent.com/10928828/33373030-68b2693a-d500-11e7-9a12-2254bad91364.png)

What it looks like when browsing with Just-Read:

![image](https://user-images.githubusercontent.com/10928828/33373076-98084e48-d500-11e7-96ce-2c43d3302023.png)

A shot from developer console in chrome:

![image](https://user-images.githubusercontent.com/10928828/33373132-d1881676-d500-11e7-870d-5d7b276f6c49.png)

Thank you for taking your time reading this post.

**Comment by ZachSaucier** [comment]
Thanks for the report! This actually isn't due to the elements in question being inside of a fieldset tag, it's due to them having class names of "series-nav-left" and "series-nav-right". There is a rule in Just Read's default stylesheet of 

```
[class *= "navigation"], 
[class *= "nav"],           /* This is the one in use */
nav, [class *= "search"], 
[class *= "menu"], 
[class *= "print"]:not(.simple-print) {
    display: none;
}
```

which hides the elements being referenced. 

As I believe that in general this rule hiding navigation is generally a positive thing on most sites, I am currently not going to remove this rule from the default stylesheet. However, you can customize your stylesheet to not select this specific class instance by changing `[class *= "nav"]` to `[class *= "nav"]:not(.series-nav-left):not(.series-nav-right)` or something like that if you would like.

**Comment by Rudoslav** [comment]
Thank you for the response. I will try to modify the stylesheet.

**Comment by ZachSaucier** [comment]
Let me know if you run into any problems!
