### ISSUE TITLE
Problem website report: unwanted content output

### ISSUE THREAD

**Issue by megadr01d** [ZachSaucier/Just-Read#125]
Just to report a website that makes Just Read output unwanted content (menus, buttons, related articles, etc.). Feel free to add in more websites which exhibit the same behavior in this issue.

http://www.healthy-holistic-living.com

**Comment by megadr01d** [comment]
More strangeness related to the domain above, two different articles, one works, the other doesn't.

Broken: http://www.healthy-holistic-living.com/optical-illusions.html
Working: http://www.healthy-holistic-living.com/unhealthy-relationship-signs.html

**Comment by ZachSaucier** [comment]
That site has a ton of loaded scripts and stylesheets being loaded in the `<body>`... Ew.

The reason why this is happening is because the disclaimer on the site has more words than any paragraph in the actual article. Since the footer that the disclaimer is in is on the same level as the article content, Just Read selects more generally and selects the whole body, which includes a bunch of scripts and styling that are (mis)placed in the body. 

As such, this is pretty much a won't-fix issue unless the approach of Just Read's auto-selection is changed because sites really shouldn't have this styling and stuff inside of the body. 

You can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to work around issues like this.

**Comment by megadr01d** [comment]
You're right, the website is incredibly bad coded. I'll use user selection mode when needed and you can tag this won't-fix (as a reference to users which have issues with this or similar websites).

Thanks, closing.
