### ISSUE TITLE
Text not shown

### ISSUE THREAD

**Issue by talbotsk** [ZachSaucier/Just-Read#127]
https://nanicmama.sme.sk/ja-mama/detska-dusicka

**Comment by ZachSaucier** [comment]
Thanks for the report! The actual problem is that the comments section is auto-selected, which already has an open issue: https://github.com/ZachSaucier/Just-Read/issues/94 So I'm going to close this issue as a duplicate and add the problematic site to the list. 

Until it's fixed, you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to work around the issue.

**Comment by talbotsk** [comment]
Hi Zach,
 
  thank you for very quick response. Thank you for your hint about user selection mode. This is great extension!
 
  B.
______________________________________________________________
> Od: Zach Saucier <notifications@github.com>
> Komu: ZachSaucier/Just-Read <Just-Read@noreply.github.com>
> Dátum: 17.12.2017 17:57
> Predmet: Re: [ZachSaucier/Just-Read] Text not shown (#127)
>
Thanks for the report! The actual problem is that the comments section is auto-selected, which already has an open issue: #94 <https://github.com/ZachSaucier/Just-Read/issues/94> So I'm going to close this issue as a duplicate and add the problematic site to the list.
Until it's fixed, you can use Just Read's user selection mode <https://github.com/ZachSaucier/Just-Read#user-selection-mode> to work around the issue.
