### ISSUE TITLE
Ignores one <h2> tag on this page

### ISSUE THREAD

**Issue by pato7** [ZachSaucier/Just-Read#128]
Probably duplicity to #88.

On [https://winaero.com/blog/reset-folder-view-folders-windows-10/](https://winaero.com/blog/reset-folder-view-folders-windows-10/) it ignores header  `<h2>` "Reset the folder view for all folders in Windows 10" and skips it. Probably because it contains additional parameter `<h2 data-simple-delete="true">`, the other `<h2>` on the page (without additional parameter) is fine.

When I look at ti one more time (I spotted the same behaviour on a different page [SME.sk](http://sme.sk/)) the original header is ignored and first `<h2>` is used instead - moved from original position to the top.

**Comment by ZachSaucier** [comment]
It's missing because it was taken from the article and into the Just Read title. I need to try to reconfigure how to find correct titles on pages at some point, so this issue will likely stay open until I can find a better method of finding article titles that's more reliable. Thanks for the report!

**Comment by ZachSaucier** [comment]
This should be fixed as of JR version 1.1.4.
