### ISSUE TITLE
Omits first para

### ISSUE THREAD

**Issue by SpiderJonny** [ZachSaucier/Just-Read#132]
https://www.lrb.co.uk/v40/n02/gavin-francis/the-untreatable

**Comment by ZachSaucier** [comment]
Thanks for reporting the issue!

This seems to be an extreme edge case due to a semantic separation in the way they have the article structured (seeming because of an unused drop cap property). I don't know that Just Read will be able to fix errors like this without massive modification to the auto-selection approach. 

However, you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the full article on problematic pages like this.

**Comment by SpiderJonny** [comment]
Many thanks for the quick reply.
