### ISSUE TITLE
Just-Read ignores H1 in article

### ISSUE THREAD

**Issue by Leolik** [ZachSaucier/Just-Read#134]
Just-Read extension ignores H1 tag and show me next H2 as title.

link for test: https://zen.yandex.ru/media/akov/poleznyi-aliexpress-14-kachestvennaia-tehnika-za-kopeiki-5a6c7cf3256d5cca602b7cf1

I like this plugin but problem with title I see on many sites ((

P.S. sorry for my English

**Comment by ZachSaucier** [comment]
Thanks for the report! The reason for this is because it checks the article content for any titles before checking more generally. 

The approach used in the title selection needs to be changed but I'm unsure how to improve it generically, given many sites use H1s as their site title, not their article title.

**Comment by Leolik** [comment]
in this case H1 placed inside <article>, maybe this help

**Comment by ZachSaucier** [comment]
It's placed inside a more general container, but still in a different container than most of the article's content. Relationally in terms of semantics it's more like a cousin than a sibling if that makes sense.

**Comment by ZachSaucier** [comment]
This should be fixed as of JR version 1.1.4.
