### ISSUE TITLE
`Esc` closes JR when exiting out of browser's search functionality

### ISSUE THREAD

**Issue by ZachSaucier** [ZachSaucier/Just-Read#137]
<kbd>Esc</kbd> closes JR when exiting out of browser's search functionality (<kbd>CTRL</kbd> + <kbd>f</kbd>). I need to somehow change the hotkey so it only happens when Just Read is selected, not any part of the browser's menus. I'm not sure how to do this given I don't know if we can detect anything directly about Chrome's search functionality using JS. the document retains focus when the search function is up, and the search function can also be closed by using the `x` button.

**Comment by ZachSaucier** [comment]
I was able to solve this issue after I realized that Chrome closes its search functionality `onkeydown`, not `onkeyup` like I mistakenly assumed.

**Comment by rhtCanuck** [comment]
I"m not 100% sure my comment is related to this closed issue.  but in case it is, i'm putting it here. There's an easy workaround ( for me anyhow) so I think of it as more of an FYI.  I'm on windows 10 and using google chrome. I use this extension a lot, copying ebook pages into a separate learning app. If I open a page, 'JR' it, copy it , then hit ESC to un'JR' it,  to go to another page in the ebook, and repeat the process....after several iterations , the browser just closes completely, no error message.  Thankfully the google chrome version i have is pretty friendly with its 'reopen closed window' ( chrome canary) but its still kinda frustrating. I discovered tho, that if instead of using ESC to de'JR', if i just hit the extension again, either from the browser toolbar, or context menu, it de'JR's just fine and i have not seen a crash since.  I'm mostly logging this here in case others have seen this.
thx.

**Comment by ZachSaucier** [comment]
Interesting. Thanks for the info, @rhtCanuck!
