### ISSUE TITLE
[ request ] Syntax and text color Highlighting

### ISSUE THREAD

**Issue by AhmedNazir** [ZachSaucier/Just-Read#142]
when seeing Source Code or Text which highlighted by Multiple Color is not found like original in Just Read Mode. Just Read make it black and white. Syntax Highlight is very helpful for the article which has source code.

Thanks in Advance....

**Comment by ZachSaucier** [comment]
Thanks for leaving a comment! Can you please provide an example link of a page that has the highlighting that you're referencing?

**Comment by ZachSaucier** [comment]
Also, most `<code>` elements go inside of `<pre>` tags (as they usually should). As such, the "Don't reformat pre tags" options in Just Read may be of interest to you. It will make JR not touch anything inside of `<pre>` tags.

**Comment by AhmedNazir** [comment]
https://paste.ubuntu.com/p/2nnYC5zWMd/

it will be awesome if it shows code with syntax highligting...

**Comment by ZachSaucier** [comment]
Ah, I see what's going on. When the "Don't reformat pre tags" option in JR is checked, it retains the same HTML but doesn't retain the separate CSS when it's not within the pre tags. In order to fix this I'll have to see if the "Don't reformat..." option is checked, see if anything within the pre tags has a class, then search for the class selector inside of the page's CSS stylesheets in order to find and retain only the relevant CSS stylesheet. This could, however, lead to other problems of other elements being styled if they also have styling in that same stylesheet, so I can't promise I'll be able to do this well (if at all). But when I find some time to check I'll update you.

**Comment by ZachSaucier** [comment]
Looking more into the feasibility of this, it seems like more work than it's worth. As such, I'm going to close this for now, but if someone else wants to give it a shot themselves I'll be happy to help out where I can.

**Comment by liskin** [comment]
I've had some success with including a highlight.js theme verbatim in my Just-Read theme: just paste the contents of e.g. https://github.com/highlightjs/highlight.js/blob/master/src/styles/vs.css at the end of the style css in Just-Read configuration. Hope this helps. :-)
