### ISSUE TITLE
Rendering - Slashdot

### ISSUE THREAD

**Issue by h3298** [ZachSaucier/Just-Read#144]
https://news.slashdot.org/story/07/06/20/1356207/embedded-linux-primer

**Comment by ZachSaucier** [comment]
This is because Just Reads selects the content but attempts to hide it in the default stylesheet because all of the content is technically comments. Given the linked website is just a forum which doesn't meet Just Read's intended purposes, I think the current behavior is acceptable. You can work around this issue by using Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode).

**Comment by ZachSaucier** [comment]
Notice that you can now also optionally disable Just Read's hiding of this content by unchecking "Use hide-segments.css" at the bottom of Just Read's options page.
