### ISSUE TITLE
Auto-enable for certain sites

### ISSUE THREAD

**Issue by insanityfarm** [ZachSaucier/Just-Read#15]
Great extension! I'd love the ability to auto-activate Just Read on certain sites. A user-configurable list of domains in the options screen would probably be sufficient. Have you thought about implementing such a feature?

**Comment by ZachSaucier** [comment]
I've thought about some similar features using a couple different means but not exactly in this way. This way seems achievable and limited in scope, which is good. I can imagine it possibly be annoying, but it's worth exploring/testing for sure.

Some questions I have regarding user expectations of the feature (I have my own answers to this but I'm curious what you think for each): 

- How can Just Read determine that a page's content is loaded _fully_? 
- What happens _before_ Just Read is ready?
- What happens when the Just Read version is _closed_?

**Comment by ZachSaucier** [comment]
I implemented this feature in 94144f0 / 1.0.8 but have done minimal testing thus far. You can optionally enable it on the Options page under "Auto-run domain list".  To do so, just include the domains that you want Just Read to run on, such as the following:

```
www.nytimes.com
www.redandblack.com
```

Note that the current functionality is based completely off of the *domain*, including the "www." or not (so if a site has both www. and not, you need to include both in the list). It's possible that we may want to change the functionality to search the URL for a specific string, such as `somenewswebsite.com/articles/` so that the non-article pages are not affected. and it gives more freedom. Let me know what you think.
___

Answering my own questions from the post above for completeness (for how it currently works):

- I decided to run Just Read on `window.onload`, which will show the original page's contents but open the Just Read format as soon as the window says it's ready. 
- I decided against trying to use a different overlay to try and hide the original page contents because by the time Just Read *could* do that, the page would have showed for a little while anyway.
- Since the page loads normally until it is fully loaded, at which point Just Read runs, closing it has no issue closing, it's the same as normal.

**Comment by insanityfarm** [comment]
Fantastic follow-through, thanks very much. I'd meant to write up some responses for you but got caught up in work. Just got the notification of your update this morning... sorry for leaving you hanging.

I haven't had a chance to try out your implementation yet but the logic you describe seems reasonable. Shame about the visual flash before `window.onload` but I understand why you needed to do it that way. It's probably not an issue when you get used to it.

**Comment by ZachSaucier** [comment]
Notice the change in functionality since posting: as of version 1.0.9 it will search the given URL vs the new page's URL to determine whether or not it should auto-run Just Read.

Thanks for suggesting the feature!

**Comment by ZachSaucier** [comment]
FYI I'm loving this feature, haha

**Comment by ZachSaucier** [comment]
I just added another related feature in version 1.0.11 where users can open an article in Just Read form by right clicking a link to the article then clicking "View the linked page using Just Read", which will load the link in a new tab and automatically run Just Read on it (without having to add it to a domain list or navigate to the page and manually open Just Read). 

I looked into creating a keyboard shortcut for this, like <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + Left-click on a link, but couldn't figure out how to properly get it working.

**Comment by ZachSaucier** [comment]
In order to give more control, I switched this over to use JavaScript's `new RegExp(str, "i")` and `url.match( regex )`. Thus the original functionality is retained but you can now do things like the following:

- To search the whole URL for a given string: `givenString`
- To get URLs starting with a given string: `^(givenString)`
- To get URLs ending with a given string: `(givenString)$`

or any other valid Regex expression. You can play around with string and expression matching [here](https://jsfiddle.net/trmszwjz/1/). See [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) for more information. 

I am using the ignore case `i` flag currently because I think it's most appropriate, though I'd be open to discussing whether or not that should remain.

**Comment by ysamjo** [comment]
This is brilliant and the sole reason I installed the extension.

Personally I want to use Just Read everytime I read an article.
Is there a crowdsourced Google Doc or else that collects magazine/blog URLs?

At which point the system would bog down, because of too much regex parsing?

**Comment by ZachSaucier** [comment]
@ysamjo I'm glad you like it!

So far the answer is no, there isn't a crowdsourced list of article-type websites. But you're free to start one! If you do, make sure that the regex selects only article-type pages of a given websites as much as possible, meaning probably not the home page of many websites but preferably only the article pages. I realize that this isn't always possible to do.

As for bogging down your browser or Just Read, the only thing it could do it increase the amount of time it takes for Just Read to start. JavaScript is pretty fast, so the list would have to be long for it to make any noticeable affect.

With all of that being said, the reason why I don't attempt to have a running list is because it's likely to be error prone, especially given time, and many people are okay with reading articles on some webpages because the built in styling isn't horrid, whereas on specific other sites the built in styling is so bad that they really need to use Just Read.

**Comment by gouravkr** [comment]
Can you help me understand this feature a bit?
What I want to do is this:
I want to auto enable it on www.livemint.com only if the url ends with .html
However, I do not want to enable it if it is something like www.livemint.com/query/****.html i.e. there is the string query after the first /

How can I do this?

**Comment by ZachSaucier** [comment]
It checks using regex format. I'm not very good at regex, so this could likely be improved, but this should work for you: 

```
    ^(?=^http:\/\/www\.livemint\.com)((?!\/query\/).)*$
```

**Comment by sinhthanh** [comment]
I love selected text and deletion mode features. But can you have some kind of undo for deletion? sometimes I accidentally delete the wrong part or even the whole main text, then I have to do the deletion from the beginning.

**Comment by ZachSaucier** [comment]
@sinhthanh Yes, that's a good suggestion. I'd likely implement undo for title/author changes as well - a more full undo functionality. I'll make a new issue requesting it.

**Comment by ysamjo** [comment]
@ZachSaucier I experienced that a lot of blogs are structuring their URLs as follows:

http(s)://name.tld/year/month/day/ID/articlename
For example: https://www.theverge.com/2018/5/29/17406958/carrot-weather-malicious-ai-app-android-early-beta

Can you tell me the Regex to single out every URL that has a /20* behind the TLD?
Thanks in advance and keep up the good work.

**Comment by ZachSaucier** [comment]
@ysamjo A (crappy) way to do this would be to use `(?=\.*)/20`, which matches with any URL that has a `/20` after a dot something. So it'd match `domain.com/something/2042` in addition to what you're asking for. You may need something more specific than that.

**Comment by ZachSaucier** [comment]
Just Read allows for sites to automatically be added to the auto-run list and there is an optional context menu entry to add the current page to the auto-run list. See [this post](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-auto-run-just-read-on-specific-websites) for more.
