### ISSUE TITLE
Turkish character doesn't show up correctly

### ISSUE THREAD

**Issue by callofktulu** [ZachSaucier/Just-Read#154]
Turkish alphabet characters, ş, ğ and ı doesn't show up correctly. A meta utf-8 problem probably.

**Comment by ZachSaucier** [comment]
Thanks for the report! Can you please provide a site or two that has this issue? Using this GitHub issue as an example, I can't recreate the issue.

**Comment by callofktulu** [comment]
http://www.hurriyet.com.tr/yazarlar/dogan-hizlan/yeni-opera-binasi-icin-oneriler-40824210
http://t24.com.tr/yazarlar/hasan-cemal/ya-demokrasi-ya-diktatorluk,19605

I realized that the problem is with the "ş/Ş" letter only.

**Comment by ZachSaucier** [comment]
Can you please add a screenshot of what the problematic rendering looks like for you? I'm still not noticing the error, but that very well could be because I'm unfamiliar with Turkish.

**Comment by callofktulu** [comment]
![capture](https://user-images.githubusercontent.com/5358044/39577158-cc1efb5a-4ee0-11e8-9215-976f0cb86599.PNG)

The letter "ş" is shown smaller/with a different font.

**Comment by ZachSaucier** [comment]
Ahhh, that's what you mean. Yes. This is because the default font does not have a special character for that Turkish letter. So the browser naturally falls back to a font that has that character supported (`serif` in this case). If you use change your JR stylesheet to use a font that supports this character, it will work as desired. 

As such, it's technically not a problem with JR, rather with the font that JR defaults to, but I'll look into similar fonts that support this character in the future and may change the default font. I probably won't get around to that for a while.

**Comment by ZachSaucier** [comment]
I can't really find a similar enough (free) font to use as the default that has the glyphs that Turkish needs. If you (or someone who sees this) finds a good replacement, let me know. Otherwise you can change the font yourself in your theme.

Closing this for now.
