### ISSUE TITLE
Replace the browser's CTRL + F search functionality to only match within JR's format

### ISSUE THREAD

**Issue by patovoador** [ZachSaucier/Just-Read#160]
Hello. 

I've just installed the extension on my Google Chrome browser in order to facilitate my reading of my country Laws, and I'm having a problem when using the search function (Ctrl+F).

For example, when I press Ctrl+F for the term "2017" on this [link](http://www.planalto.gov.br/ccivil_03/constituicao/constituicaocompilado.htm), I've have 29 results to look on.

But, on the same page, when the extension is active, if I press Ctrl+F to search for the same term "2017", it will show me twice the results (58). And, the first 29 can't be seem. I can only "jump" from the 30 to 58 result. I imagine that the first 29 are hidden "behind" the Just-Read modified text.

Is there a fix to this?

Thank you very much. 
Greetings from Brazil.

**Comment by ZachSaucier** [comment]
Thanks for the report! I was aware of this issue but hadn't given any thought of whether or not I could fix it. 

After researching it, it seems like the whole search functionality would have to be replaced. That seems doable but is not very high priority. So I'll leave this issue open as a feature request.

**Comment by ZachSaucier** [comment]
I replace the whole search functionality in the premium version of Just Read in order to fix this issue. It doesn't work perfectly like Chrome's search functionality, but it's usable enough I think. It makes use of the same technology as the highlighting/annotating functionality, so it's restricted to the premium version for now. See [Just Read's homepage](https://justread.link/) for more information about the premium version.
