### ISSUE TITLE
Just Read on Reddit

### ISSUE THREAD

**Issue by kdbeall** [ZachSaucier/Just-Read#162]
Would love to be able to use Just Read on Reddit when I'm reading TalesFromTechSupport.

[The post](https://www.reddit.com/r/talesfromtechsupport/comments/8vj5p9/tales_from_aircraft_maintenance_the_end_of_an_era/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=talesfromtechsupport)

![screen shot](https://user-images.githubusercontent.com/10102694/42231036-7596b036-7eb8-11e8-8938-e02b68702ded.png)

**Comment by ZachSaucier** [comment]
Hey and thanks for the report! 

This is because Just Read's default stylesheet contains a CSS line that hides all `<form>` elements inside of the selected content. For some reason Reddit (or at least this subreddit) puts all of user's posts inside of a `<form>`. 

As such, you can remove the `form,` (or change it to `form:not(.usertext)` ) from the default stylesheet and it should show. I'll update the default stylesheet to include this change in future versions of JR since Reddit is such a big source of readership. 

```
form, [class ^= "form-"], [class ^= "form"], [class *= "-form-"], [class $= "-form"], [class $= "form"], [class ~= "form"]
```

**Comment by tbc** [comment]
This is the first time I've tried JR at Reddit. It happened to me today. Problem post: https://www.reddit.com/r/engineering/comments/2o9dho/the_empty_toothpaste_box_problem/

Is this a regression?

**Comment by tbc** [comment]
@ZachSaucier ah, thanks. I had never tried user selection mode. Loving it!
