### ISSUE TITLE
Article headline is shortened, subheading is removed (theguardian.com)

### ISSUE THREAD

**Issue by baz357** [ZachSaucier/Just-Read#165]
"The George Soros philosophy – and its fatal flaw" becomes "The George Soros philosophy"
and
"Unlike most of the billionaire class, George Soros is not an out-of-touch plutocrat, but a provocative thinker committed to progressive ideals – which is what makes his failures so telling." is missing.

https://www.theguardian.com/news/2018/jul/06/the-george-soros-philosophy-and-its-fatal-flaw

**Comment by ZachSaucier** [comment]
Thanks for the report.

This is not likely to be fixed any time soon because it is more common for non-essential content to come after dashes inside of titles like that. You can work around the issue by manually editing the title (by hovering over it and then clicking the pencil icon that pops up). 

Just Read is also not currently set up to be able to handle subtitles like that. They are pretty rare and their formatting varies drastically, so it'd be a hard task for JR to do.

**Comment by baz357** [comment]
Ah, I see. Well, not *that* big of a problem. :)

Yeah, regarding the pencil... I don't really get it. Why would anyone use it? I just changes what's displayed right now.

**Comment by ZachSaucier** [comment]
It's mainly for people who are going to print the article. And would be useful if JR ever her a permanent save feature.

**Comment by baz357** [comment]
> It's mainly for people who are going to print the article.

Ah, interesting... That's a use case I never considered.

**Comment by ZachSaucier** [comment]
Closing this since there's not really an issue that can be fixed right now.
