### ISSUE TITLE
Requested enhancement: auto-read

### ISSUE THREAD

**Issue by github-clearthought** [ZachSaucier/Just-Read#169]
When the user clicks on the extension to go into reading mode, the extension should save the domain name of the page, and then whenever a page is loaded from that domain, the extension should automatically put the page in reading mode.

If the use clicks on the extension to exit reading mode, the extension should remove the domain name from its list, and then no longer automatically put pages into reading mode for that domain.

**Comment by ZachSaucier** [comment]
Thanks for the suggestion! 

The first part has actually just been implemented (in part because of #166). The second part is counter to how some users use the extension (I've seen several people who use the button to both open and close JR) and is not an intuitive action. 

As such, there's no more to be done in regards to this issue.
