### ISSUE TITLE
Niche Issue: Display problems with the Oxford Handbooks site

### ISSUE THREAD

**Issue by osmanas** [ZachSaucier/Just-Read#17]
Using the extension on an Oxford Handbooks article misses the content text and instead only displays references. 
![screen shot 2016-10-27 at 6 44 36 pm](https://cloud.githubusercontent.com/assets/23097599/19764409/6ef9c9a6-9c75-11e6-9854-29122ac33d94.png)
![Uploading Screen Shot 2016-10-27 at 6.44.28 PM.png…]()

**Comment by ZachSaucier** [comment]
Hey osmanas, thanks for reporting the issue.

Could you provide a link to the problematic webpage? The closest I could find is [this [page](http://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780199263684.001.0001/oxfordhb-9780199263684-e-019?mediaType=Article) which I don't think is correct and doesn't have an error like you show.

P.S. Have you tried using Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) or [highlight mode](https://github.com/ZachSaucier/Just-Read#highlight-mode)?

**Comment by osmanas** [comment]
Hi Zach, thanks for the rapid response. I didn't realize highlight mode was a feature, and it clears the problem right up. By the way, this extension is incredibly useful and I'm very glad it exists.

**Comment by ZachSaucier** [comment]
@osmanas I'm glad that it helped! That's what those alternate modes are for.

With that being said, I try and make Just Read's default selection as good as possible, So if you have a link to the broken page (if it doesn't require a login) I'd still like to have it.

**Comment by osmanas** [comment]
Hi Zach, 

I'm on an enterprise network, so I'm not sure if the link is normally behind a login or not. I've attached the .htm of it in the Dropbox link below. Again, thanks a bunch for making this extension. 
https://www.dropbox.com/s/3hfn59sr23d4gd8/Accounting%2C%20Information%2C%20and%20Communication%20Systems%20-%20Oxford%20Handbooks.htm?dl=0

**Comment by ZachSaucier** [comment]
Yea, that's a very difficult case because each of the sections have their own <div> container so the way that Just Read looks for the main content won't be correct the majority of the time. 

The solution would be to change (or add) how selection is done by checking the IDs and classes of every element, looking for key ones (like content, which is within the ID `contentRoot` in this case). However, in my experimenting I've found that this method leads to more errors, at least with the simple way of searching for these elements that I tried out.

As such, I recommend to use selection or highlight mode for pages like this. In the future I may revisit this issue and try to do better selection based off of IDs/classes.

Thanks for providing the HTML and reporting the issue! Let me know if you run into any other issues.
