### ISSUE TITLE
Part of the page not displayed

### ISSUE THREAD

**Issue by glacchia** [ZachSaucier/Just-Read#181]
> - Just Read version (free/premium version as well as the specific version number if possible)
Premium 3.0.6
> - Your operating system
Windows 10 Chrome

Some parts of the page are not displayed on Just Read.

E.g. in the following page

https://www.jwatch.org/pa200805280000001/2008/05/28/needle-free-delivery-lidocaine

I cannot see on Just Read the boxed text in the COMMENT as you can see in 

https://justread.link/q3venv_qb

Thanks, 
Gilberto

**Comment by ZachSaucier** [comment]
Thanks for the report! 

This is related to #95, but not quite the same. Just Read is selecting the entire *article* content, just not the author's note (comment) or citations (somewhat purposefully). If JR did select the comment, it would hide it by default anyway because JR tries to hide all comments on a page (because most the time it's not by the author). 

With that being said, you can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to get the content you want and [disabling `hide-segments.css`](https://github.com/ZachSaucier/Just-Read/#q-just-read-isnt-selecting-all-of-the-content-i-want-it-to-what-can-i-do-to-fix-this) temporarily. 

As such, I don't think this is really an *bug* with Just Read. More so kind of an annoyance with the setup of that page.
