### ISSUE TITLE
Send to kindle without sharing

### ISSUE THREAD

**Issue by gennad** [ZachSaucier/Just-Read#184]
Are you planning to do sending to kindle without sharing? What if I want to send to kindle some private information? I would not  want it to be shared on a third-party site.

**Comment by ZachSaucier** [comment]
This is currently impossible using Amazon's "Send to Kindle" functionality. From what I can tell, when you click the button Amazon has a bot scrape the site's content, so any dynamic content pages (like Just Read's view) cannot be supported. This is a big reason why I started hosting content in order to share pages. 

With that being said, you can share the content in Just Read, send it to your Kindle device (granted this feature is working - currently I'm [waiting to hear back from them](https://github.com/ZachSaucier/Just-Read/issues/180)), then immediately delete it from Just Read's server by navigating to https://justread.link/dashboard and deleting the entry that matches the shared page that you just made. I don't keep backup copies or anything like that.

In terms of privacy, as stated in [Just Read's privacy statement](https://github.com/ZachSaucier/Just-Read/#privacy-statement), I cannot know who shares what content because it's solely associated with their Google ID which has nothing to do with your name or email. I also run no analytics on what type of content is shared.
