### ISSUE TITLE
HIGHLIGHTING AND SAVING AS PDF

### ISSUE THREAD

**Issue by SaiKumar0601** [ZachSaucier/Just-Read#189]
I just upgraded to Just read Premium, which is completing Disappointing, by reading its features I liked it a lot but it doesn't even save the highlighted texts and doesn't even print none of the highlighted text it's just like a normal page, come on man do something, about
* ALLOW HIGHLIGHTED TEXTS TO PRINT.
* MAKE A PROPER ALIGNMENT OF PAGE WHILE PRINTING.
please Don't make me feel I wasted my saving money on somewhat useless extension....please help me out of this
THIS IS VERY IMPORTANT FOR MY STUDIES

**Comment by ZachSaucier** [comment]
Hello and sorry the premium version is not exactly what you expect.

In order to keep highlighting when printing, you can simply add `-webkit-print-color-adjust:exact;` to your stylesheet inside of the `body { }` area. You can do this by going to the Options page. Make sure to save your change to the stylesheet and reload any Just Read instances that you have open before trying again.

As for the "proper alignment of the page while printing", can you please post an image example of what you're referencing?

**Comment by ZachSaucier** [comment]
If you want to "save" the highlights, you should share the page by clicking the share icon in the top right of Just Read Premium. Make sure to make any edits or highlights before you share though, because they are uneditable in a shared copy.

**Comment by ZachSaucier** [comment]
I changed the default stylesheet to include this change in JRP version 3.0.10. Closing this issue at least until more feedback is given.
