### ISSUE TITLE
Inline content missing from Just Read's selection

### ISSUE THREAD

**Issue by tbc** [ZachSaucier/Just-Read#193]
Article: https://www.atlassian.com/blog/announcements/introducing-jira-ops-incident-management-platform

**Original:** 
![image](https://user-images.githubusercontent.com/661281/45111036-21813680-b101-11e8-9014-70eca9ec0475.png)

**Bad rendering:**
![image](https://user-images.githubusercontent.com/661281/45110991-057d9500-b101-11e8-80c0-1b128741da13.png)

_Delete this inferior screenshot:_
![image](https://user-images.githubusercontent.com/661281/45110947-ee3ea780-b100-11e8-8271-59618c192071.png)

**Comment by ZachSaucier** [comment]
Thanks for the report! This is because there is an inline element that has the class `inline-comment-marker` and Just Read tries to use classes specified in the selection to hide irrelevant information (like comments). You can disable this behavior by unchecking "Use hide-segments.css" in Just Read's options, but you will likely see a lot of other non-article-content when this option is unchecked. 

Another alternative is to modify your stylesheet to include the following if you're going to use this site often and they frequently use this style rule:

```
.inline-comment-marker {
    display: inline-block !important;
}
```

**Comment by ZachSaucier** [comment]
This is a won't-fix for now since I don't think there's really a solution using JR's current approach and it can be worked and. Closing this issue for now.
