### ISSUE TITLE
Ovid books

### ISSUE THREAD

**Issue by jmngb** [ZachSaucier/Just-Read#225]
Hi Zach, first of all thanks for putting your time and effort into this. I tried using Just Read for Ovid books but it's not working even with user selection mode.

Here is the link but it unfortunately requires access
http://www.ovid.com/site/catalog/books/index.jsp

![capture](https://user-images.githubusercontent.com/46862510/51438167-6fdd3f00-1c76-11e9-8a51-446aac6c9034.PNG)

**Comment by ZachSaucier** [comment]
You're welcome!

Can try saving the page to your computer, opening the downloaded copy, and see if the error can be reproduced that way? If so send it over to support@justread.link so I can test it.

If it can't be reproduced or I otherwise get access to the page, I'm afraid I can't do anything to fix it.

**Comment by ZachSaucier** [comment]
Otherwise if *you* can figure out what's causing the issue, you may be able to recreate it in a minimal version (or at least tell me so I can *try* to recreate it that way).

**Comment by ZachSaucier** [comment]
jmngb sent me a downloaded copy of the site and I believe I was able to reproduce the bulk of the issue. 

The site has some very interesting markup, haha. I've never seen anything like it. 

There are multiple parts about it that seem to give Just Read some issues (though I'm proud of how Just Read handles some of them), but the killer is Chrome's cross-frame policy. Essentially it doesn't want to let JavaScript touch the frames on the page for security reasons. 

As such, this is a won't-fix for now because I have no idea how to circumvent Chrome's policy in this regard.
