### ISSUE TITLE
https://foodheavenmadeeasy.com/warm-maple-amaranth-porridge/ - cleaned up the article but left the recipe at the bottom (the part i wanted) off

### ISSUE THREAD

**Issue by cflisher** [ZachSaucier/Just-Read#226]
> Thanks for wanting to help improve Just Read! 
> 
> Looking through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) may help you with your request. Please look through [the existing posts](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed.
> 
> If you're submitting an error report, please include the following:
> 
> - Just Read version (free/premium version as well as the specific version number if possible)
> - Your operating system
> - Steps to recreate the issue including the relevant URL if necessary
> - A screenshot of what the page looks like (if relevant)
> 
> Please delete this text from your post before posting.

**Comment by ZachSaucier** [comment]
Thanks for the report! 

This error is because the website has `yumprint` in a lot of its class names and Just Read tries to hide things related to printing. 

To work around this issue, go to Just Read's Options page (right click on the Just Read icon and click Options) and temporarily uncheck "Use hide-segments.css" at the bottom of the page.

If you want a more permanent workaround, you can include the following in your theme that you use:

```
[class*="yumprint"] {
    display: block !important;
}
```

I don't think this warrants Just Read itself being changed at this point in time.
