### ISSUE TITLE
Just Read for Firefox?

### ISSUE THREAD

**Issue by hiya-tiger** [ZachSaucier/Just-Read#227]
Can you bring the extension to Firefox?

**Comment by ZachSaucier** [comment]
Hello, 
This is a duplicate of #135. Please keep the discussion to that thread. Thanks!

**Comment by ZachSaucier** [comment]
What is Waterfox?

**Comment by ZachSaucier** [comment]
Apparently there is such thing as [Waterfox](https://www.waterfox.net/). If it's not already supported using the [Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/just-read-ext/), I likely will not add support because it's not worth the effort. With that being said if someone else wants to do so I am open to pull requests.
