### ISSUE TITLE
Cached body text when navigating between emails on Gmail

### ISSUE THREAD

**Issue by StephanieYHe** [ZachSaucier/Just-Read#228]
## Details
- Just read v 1.5.0, free
- OS: Mac OS Mojave 10.14.2
- Browser: Chrome Version 71.0.3578.98

## Issue
When navigating between emails on the Gmail, clicking the `JustRead` extension will give the same cached text despite being on different emails.

## Reproduction steps
1. Navigate to `Email A`, click Just Read
2. Navigate back to inbox
3. Navigate to `Email B`, click Just Read
4. See that the `Just Read` text has an updated header text for `Email B`, but the body text is still `Email A`.

**Comment by ZachSaucier** [comment]
Thanks for the report! This is the best formatted report that I have seen for Just Read, haha.

This is very helpful. A couple days ago I actually implemented a new feature to save the content of the most recent Just Read load automatically so that it can be recovered if accidentally closed (when the URL is the same as the last load). 

But in this case it's harmful, so I will remove it from being the default. I will also make it only save the most recent copy if something has been *changed*, so it wouldn't occur in your case unless you deleted something in the article or something along those lines. 

I am pushing the changes now, but if you want to use JR with Gmail before the new version gets to you, you can go to Just Read's Options, click Additional options, then uncheck "Backup most recent Just Read page (in case of accidental closure)."

Thanks again for posting!

**Comment by ZachSaucier** [comment]
This is fixed as of JR version 1.5.1 (3.3.1 for premium).

**Comment by StephanieYHe** [comment]
Awesome, thanks for handling so quickly! The workaround also works for me :)
