### ISSUE TITLE
Images not loading from lifewire

### ISSUE THREAD

**Issue by PL47ER** [ZachSaucier/Just-Read#229]
I am trying to load the page : https://www.lifewire.com/free-and-public-dns-servers-2626062

Images on the article main section are not loading in Just Read.

I am using Windows 10 Pro x64, Chrome, Just Read free version.

**Comment by ZachSaucier** [comment]
Thanks for posting!

Just Read runs on *content that has been loaded*. Since those images load when you scroll down the page, you need to scroll down the page before you start Just Read for Just Read to have those images. 

I don't think there's a way for me to do make Just Read load images like those? I'll look into it before closing this issue.

**Comment by ZachSaucier** [comment]
It turns out this was way easier than I thought to get working. It will be included in the next version of Just Read (releasing it now). 

Thanks a lot for the suggestion!

**Comment by PL47ER** [comment]
Thank you for fixing it so fast. Glad to point it out and fixed, that helped you close two more open issues.

**Comment by ZachSaucier** [comment]
Well, they were closed already. But I updated them to let them know that Just Read's functionality had changed :)
