### ISSUE TITLE
Issue viewing a Quora page

### ISSUE THREAD

**Issue by langbeck** [ZachSaucier/Just-Read#23]
Hi,

First I would like to say that I use this pluggin every day and it's really helpful.

Now, the problem. I was visiting [this page](https://www.quora.com/Why-do-DSLR-cameras-need-shutters) today and the plugin "failed" to identify the main content of the page. It took a "Top Stories" (at the bottom of the page) as main content.

**Comment by ZachSaucier** [comment]
I'm glad you find it so useful! Thanks for the report.

Quora pages aren't really optimal for Just Read because they're not true article type pages. They generally don't have that many paragraphs per section, which is the main thing that Just Read looks for. 

With that being said, you can use a couple different means to select a particular answer (or answers) to read in Just Read:
1. Use **user selection mode** which is enabled by right clicking the Just Read button and clicking "Select text to read". This can also be enabled by using the keyboard shortcut [if you have it enabled](https://github.com/ZachSaucier/Just-Read#user-selection-mode).
2. Using **highlight mode**, which is where you can simply highlight the text you want to read by the default click and drag action, then right click that selection and click "View this text in Just Read".

That should let you read these short answers in the Just Read format.

**Comment by langbeck** [comment]
"User selection mode" worked just fine.
I didn't know this feature.
Thanks very much.
