### ISSUE TITLE
Incorrect author on Stefanv.com

### ISSUE THREAD

**Issue by svorkoetter** [ZachSaucier/Just-Read#248]
When using Just Read on, for example, http://www.stefanv.com/electronics/a-compact-home-made-raspberry-pi-tablet.html and clicking the Just Read icon, the article is attributed to Michael Horne. I'm not sure where Just Read is getting this from, since (a) the site doesn't mention the author name for any articles (since they're all by me, the owner of the site and author of this issue), and (b) no one with that name has anything to do with the site.

**Comment by svorkoetter** [comment]
Follow-up: It seems to be getting the attribution from the author of the first comment.

**Comment by ZachSaucier** [comment]
Thanks for the report! How do you *expect* Just Read could get the correct author on this page? 

With that being said, comments should not be selected because they're in the blacklist... I'll take a closer look when I get some more time next week. 

Keep in mind that you can manually edit any incorrect meta info by hovering it and clicking the pencil icon!

This issue is related to #75.

**Comment by svorkoetter** [comment]
On Mon, 08 Apr 2019 17:52:38 -0700
Zach Saucier <notifications@github.com> wrote:

> Thanks for the report! How do you *expect* Just Read could get the
> correct author on this page? 

It can't really. The page doesn't indicate the author anywhere except by his picture in the banner. I suppose you could use facial recognition. :-) :-)

Stefan

-- 
Stefan Vorkoetter
Senior Architect
Maplesoft

**Comment by ZachSaucier** [comment]
It turns out that I actually wasn't checking against the blacklist for the meta information like I thought I was... So I added that and it now selects your correct author name! 

Pushing the changes to live now.
