### ISSUE TITLE
Formatting issue of figure cpations when reading articles from pubmed

### ISSUE THREAD

**Issue by OmriNach** [ZachSaucier/Just-Read#250]
I am using the free version of Just Read on windows to more comfortably read scientific articles from pubmed. The issue is how just read handles figure captions and figures. The text shrinks to a single column that can only fit a few letters so it becomes this long column of jumbled letters. Additionally the figure doesn't show up very well. 
![justreadissue](https://user-images.githubusercontent.com/32659330/56056942-9d90cc00-5d2b-11e9-87f7-3f7c047d88ed.PNG)

Here's the article for reference: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5373139/

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

This is due to Just Read's styling of `[class *= "emoji"], [class *= "icon"] { width: 1em; }`, which is meant to size emojis and icons correctly. However on this website, they use a class called `iconblock` on all of their figures.

I recommend that you edit your stylesheet and add the following: 

```
[class *= "emoji"], [class *= "icon"]:not(.iconblock) { width: 1em; }
```

**Comment by OmriNach** [comment]
This fix worked! thank you

**Comment by ZachSaucier** [comment]
Happy to help.
