### ISSUE TITLE
JustRead throwing in some sites.

### ISSUE THREAD

**Issue by Zyst** [ZachSaucier/Just-Read#251]
### Steps to recreate the issue including the relevant URL if necessary

1. Get a clean chrome install, with no other plugins

![clean install image](https://user-images.githubusercontent.com/3832380/56302316-1793cd00-60ff-11e9-8e3b-64b914721bba.png)

2. Try to trigger JustRead in any https://wuxiaworld.com page

![image](https://user-images.githubusercontent.com/3832380/56302395-44e07b00-60ff-11e9-9a0c-9f2c22738b45.png)

3. An error says that `className.indexOf` is not a function

I imagine some undefined check is being passed by, not 100% sure. I think I've seen this in at least one more site other than Wuxiaworld, but it's fairly uncommon.

### Current workaround

Currently I just do outline.com/https://whatever-I-wanted-to-read.com and then use JustRead on that page.

**Comment by ZachSaucier** [comment]
Thanks for the report! 

I am not able to reproduce this behavior. In the problematic line listed, I have `typeof className != "undefined" && className.indexOf(blacklist[i]) >= 0`, which should check for undefined... I'm not sure what is happening. Maybe changing it to `typeof className !== "undefined" && className.indexOf(blacklist[i]) >= 0` would help. Do you want to try that change on a local copy of Just Read? If so, see [this FAQ post](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-run-just-read-from-a-local-copy-on-my-computer) for more info. If not, I can just upload a new version with that change because it shouldn't affect any other behavior.

**Comment by Zyst** [comment]
Thanks for the quick answer Zach, I opened a PR related to this.
