### ISSUE TITLE
List Display Errors

### ISSUE THREAD

**Issue by DUSKR-09** [ZachSaucier/Just-Read#256]
BUG:
The page has 10 list items but in the "Just Read" view it takes the blank space before the list as a member of itself ending the list on 11 instead of 10

**To Reproduce**
just activate the just read mode

**Expected behavior**
the list must have only 10 items, the first (blank space) must not be considered as a member of the list

**Screenshots**
![image](https://user-images.githubusercontent.com/44409288/57393194-d7fd5580-717f-11e9-9e0f-1b477a7b8970.png)

**Please complete the following information:**
 - OS: Windows 10 - Home Edition
 - Browser: Google Chrome
 - Version: 74.0.3729.131 (Build oficial) (64 bits)

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

Could you please provide the problematic URL so I can debug what is really happening here?

**Comment by DUSKR-09** [comment]
I don’t know if its an error of the page sintax or an error of your app, i have no su much time right now so i didn’t verified that, here’s the link

https://www.monografias.com/trabajos56/etica-informatica/etica-informatica2.shtml

Enviado desde Correo para Windows 10

De: Zach Saucier
Enviado: miércoles, 8 de mayo de 2019 10:58
Para: ZachSaucier/Just-Read
CC: DUSKR-09; Author
Asunto: Re: [ZachSaucier/Just-Read] List Display Errors (#256)

Hello and thanks for the report.
Could you please provide the problematic URL so I can debug what is really happening here?

**Comment by ZachSaucier** [comment]
This is an error caused by the syntax on the original page. I have no idea why they have this element there. 

![image](https://user-images.githubusercontent.com/3966722/57393766-ca50cb80-7191-11e9-8f66-a490d9b6bdc8.png)

To work around this issue, simply use Just Read's deletion mode to delete the extra list item. For more information about deletion mode, see [the FAQ post](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-delete-parts-of-the-page-once-just-read-has-started).

**Comment by DUSKR-09** [comment]
that's it XD
