### ISSUE TITLE
Inline emoji image rendering at 100% paragraph width

### ISSUE THREAD

**Issue by RShergold** [ZachSaucier/Just-Read#26]
Just want to start by saying I absolutely love this plugin. You're doing a great job.

while reading http://fortune.com/2016/12/09/magic-leap-ceo-tech-hype/
I noticed that a small inline emoji ends up being 100% width. 

Looking at it, it seems like a really hard thing to put into a general rule as they are loading a huge svg and then giving it an emoji class to shrink it to 1em.

Maybe check the computed style and if it's 1em, and surrounded by text nodes, presume it's an inline emoji?

**Comment by ZachSaucier** [comment]
Hey and thanks for the report and kind words!

As you likely know, this is because they are using an SVG instead of the real emoji character (😎). Just Read handles regular emojis just fine, as you can test on [this test page](https://zachsaucier.com/%F0%9F%98%8E.html). 

The better way we can handle this is to include `.emoji { width: 1em; }` in our stylesheet. You can do this in your version, but the next version of Just Read will have this line included in the default stylesheet because I believe that it's generic and common enough to remain useful.

**Comment by borekb** [comment]
Hi, I'm seeing a similar problem on this page: https://pento.net/2018/08/06/wordpress-gutenberg-the-long-view/

Is it the same issue or should I open a new one? Thanks.

**Comment by borekb** [comment]
@ZachSaucier Thanks, I have had Just Read installed for a very long time so maybe it was related to that (I'm not even sure if I customized the styles or not at some point).

I've uninstalled and re-installed Just Read and the issue is gone.

BTW, I just learned about Just Read Premium, it looks good, especially if it can somehow sort out the mobile story for me. For example, I load some crappy webpage in mobile Chrome and I could share the article to a Just Read app which would be the plain view (the app could be just a small redirection helper from the full URL to `justread.link` version; the actual rendering would be in mobile Chrome again).

**Comment by ZachSaucier** [comment]
@borekb Currently when you share a page in premium the link it creates is viewable in mobile. 

On the to do list is research the feasibility of doing what I think you're suggesting - to create a way to share a page in the JR version for mobile Chrome. The mobile version wouldn't have the ability to customize all of the options like the Chrome extension has.

**Comment by borekb** [comment]
Thanks, I'll subscribe to support your work on this great extension, even if the real value for me comes when/if you get to the mobile story :)

BTW, currently, in the non-premium version, there is a submenu for "Add this page to Just Read Plus [...]" in the context menu which is slightly annoying (and I don't think the label is correct either as the service seems to be called "Premium").

**Comment by ZachSaucier** [comment]
Thanks for catching that! It was a copy-paste error from when I was implementing that feature. It should be fixed as of JR 1.2.3.
