### ISSUE TITLE
Doesn't display facebook post comments, only the original post

### ISSUE THREAD

**Issue by thmbaker** [ZachSaucier/Just-Read#261]
**Describe the bug**
The plugin Doesn't display facebook post comments, only the original post

**To Reproduce**
1. Go to facebook.com
2. Click on post
3. Click on plugin
4. See error, no comments visible

**Expected behavior**
Show comments below original post

**Please complete the following information:**
 - OS: W10
 - Browser chrome
 - Version version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**

**Comment by ZachSaucier** [comment]
Hello and thanks for posting. 

This is because on the vast majority of websites, any elements with class names related to Facebook means it's a "share to Facebook" related element. To prevent this error for happening, simply uncheck "Use hide-segments.css" in Just Read's options panel. I recommend checking it again whenever you are done reading posts on Facebook, but that's up to you.

**Comment by ZachSaucier** [comment]
Hello and thanks for posting. 

This is because Just Read hides comments by default. To show the comments, simply uncheck "Use hide-segments.css" in Just Read's options panel. I recommend checking it back again when you're done reading the comments, but that's up to you.
