### ISSUE TITLE
code boxes empty ...www.firegiant.com/wix/tutorial

### ISSUE THREAD

**Issue by bigjapko** [ZachSaucier/Just-Read#264]
...on pages:

https://www.firegiant.com/wix/tutorial/getting-started/the-files-inside/
https://www.firegiant.com/wix/tutorial/getting-started/useful-extras/

regards
B.

**Comment by ZachSaucier** [comment]
Hello and thanks for posting.

This issue is caused by the style rule `[class $= "-tag"] { display: none; }` inside of JR's `hide-segments.css` file. 

You can work around this issue by unchecking the box "Use hide-segments.css" on Just Read's options page. I'd recommend checking it back again after you read articles on that website though, as it prevents a lot of other crud from showing :) One other way is to work around it is to include something like `pre [class $= "-tag"] { display: initial; }` in your personal stylesheet. This will override the hiding.

I think I'll add something along the lines of `pre * { display: initial !important; }` to make sure that things inside of `pre` tags show up, given they are likely rarely used to hide non-article-related content.

**Comment by bigjapko** [comment]
Thank you very much :-)

śr., 10 lip 2019 o 16:48 Zach Saucier <notifications@github.com> napisał(a):
