### ISSUE TITLE
Last line lost when printing to PDF

### ISSUE THREAD

**Issue by RBoogaard** [ZachSaucier/Just-Read#268]
Whenever I print a Just Read webpage to PDF the last line either gets lost or split so half is on one page and half on the next (I'm a Premium user). Thanks

**Comment by Spivoran** [comment]
Hi I have the same issue. Working on Chrome for OSX. I also use a larger font size and don't know if that contributes to the problem. I have found that one way to work around the problem is to change the margins setting from default to either none, minimal, or custom (requiring further adjustment) when saving the PDF. It appears that the browser is not respecting JR's layout WRT margins and cutting them off. It could be a Chrome bug or something wrong with JR's stylesheets. The resulting lack of margins is unsightly, but I'm most concerned about capturing the text.

Additionally, you can play with scale, margins and headers and footers to get something a little more readable, but sometimes the footers end up on top of the page text.

![Screen Shot 2019-09-17 at 8 44 04 AM](https://user-images.githubusercontent.com/55453533/65058007-6355d700-d928-11e9-9a3f-87f493d5d2df.png)

**Comment by ZachSaucier** [comment]
It's definitely some sort of bug with Chrome, but if someone figures out exactly what's going wrong I _may_ be able to work around the issue by adjusting JR's styles 🙂

**Comment by laflier** [comment]
Hi Zach,

Same problem here. See https://justread.link/ljmlx3q6B and try to print it. The default margins are zero and when I change the custom margins lines are cut through at the bottom of the page. Just paid for the premium extension hoping it would be an improvement but in this respect, at least, it's less useful than the unpaid version.

Surprising to see that this has been a known problem in the core functionality of the extension since 2019 and still an open issue. Not good for your rep.

Here's a hint:

The original page that this file came from was in the New York Times. It's more complex than your JustRead reduction but it prints normally in Chrome. So, instead of blaming a bug in Chrome, a more constructive approach might be to look at the HTML that JustRead is generating and figure out where the problem is. 

From there, your debugging should be fairly straightforward. Just save the HTML output from JustRead and open it in an editor. Mess around with it, save it, reopen it in Chrome, and repeat until you figure out where the problem is. Then rewrite your JS to fix it. 

Actually, your problem might not even be that hard. I just tried the unpaid version of the extension (v. 2.2.8) on the same page and I can get decently formatted printed output using custom margins. Again, the debugging path is straightforward. Go back to the unpaid version and see what you changed in the paid version that created the problem.

I'd be more sympathetic but I just paid $9.00 for an extension that doesn't work and I've got development work of my own that I need to be doing. I hope you can fix this soon because I really would like to have this functionality. The whole point of JustRead for me was to be able to make clean PDFs of web pages that I can mark up in a PDF editor.

**Comment by ZachSaucier** [comment]
@laflier Thanks for the constructive part of your feedback. I'm in the process of a major update to Just Read due to Chrome's deprecation of the payments API so I'll take another look at this before I release that version.

**Comment by ZachSaucier** [comment]
I believe I was able to work around this bug by adding the following CSS:

```
@media print {
    .simple-article-container {
        display: block;
    }
}
```

This will be live in the next version of Just Read.

**Comment by ZachSaucier** [comment]
The new version including this fix is live now.

**Comment by Spivoran** [comment]
Sweet. Thanks! Your hard work is appreciated.
