### ISSUE TITLE
How can I use the premium extension on my other computers?

### ISSUE THREAD

**Issue by Zippyzeez** [ZachSaucier/Just-Read#270]
I bought Just-read premium, but when I try to download it for my other computers, it is asking me to pay the $10 again. How do I use the extension on all of my computers?

**Comment by ZachSaucier** [comment]
Hey Patrice, sorry you're running into some issues with downloading JRP.

Most likely this issue is related to which Google account you're using. Just Read Premium was bought with whatever is the main Google account that you were logged into at the time (Google allows you to log into multiple). On this new device I am guessing that your main Google account is not the same one that you were logged into. 

You can check which account(s) you're logged into by clicking the circle at the top right of your page. Here's what mine looks like: 

![image](https://user-images.githubusercontent.com/3966722/65374018-02454080-dc53-11e9-847c-eb8292face2e.png)
