### ISSUE TITLE
A post on devblog.microsoft.com is not picked up properly

### ISSUE THREAD

**Issue by nikita-r** [ZachSaucier/Just-Read#271]
Here is how a blog post at https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0/ is displayed by Just Read:
---
![image](https://user-images.githubusercontent.com/53914057/65605727-9d058e00-df77-11e9-81d4-b7b3e45766c0.png)
---
OS: Windows 10
Browser: Chrome
Version: 2.0.4

**Comment by ZachSaucier** [comment]
Hello and thanks for the report. 

This is because Microsoft's dev blogs use the class ".addtoanyshare" on the article's content. When  Just Read tries to hide superfluous stuff like share buttons, the article ends up getting hidden in this case.

As such, you can either temporarily disable the "hide-segments.css" by right clicking on JR's icon, clicking "Options", and then unchecking "Use hide-segments.css" OR you can modify your stylesheet to include the following rule:

```
.entry-content.entry-content {
    display: block;
}
```

Given this is a fairly popular site, I may end up adding this style to Just Read's stylesheets by default.

**Comment by ZachSaucier** [comment]
This should be fixed in the next version of JR.
