### ISSUE TITLE
Google Translate - no text

### ISSUE THREAD

**Issue by haakonstorm** [ZachSaucier/Just-Read#276]
Just-Read Premium doesn't show any text while having a Google Translate-translated page open.

**To Reproduce**

https://translate.google.com/translate?hl=&sl=th&tl=en&u=https%3A%2F%2Fc.mi.com%2Fthread-1827530-1-1.html&sandbox=1

2. Start Just-Read Premium

3. ???

4. No profit

**Expected behavior**
Same just-read rendering as without google translate in the middle.

**Screenshots**
<img width="1207" alt="Screenshot of Vivaldi (08-11-2019, 07-06-52)" src="https://user-images.githubusercontent.com/193781/68502179-1b846980-0260-11ea-999b-45d0a6b7b558.png">

**Please complete the following information:**
 - OS: latest macOS catalina
 - Browser [e.g. chrome, safari] vivaldi
 - Version [e.g. 22] 2.9.1705.38 (Stable channel) (64-bit)

**Comment by ZachSaucier** [comment]
Hey haakonstorm, thanks for posting.

This is because google translate pages like the one you link to make use of iframes for the page's content. Extensions (like Just Read) **cannot** have access to iframes, so there's nothing I can do in this situation. 

However, going to [the original page](https://c.mi.com/thread-1827530-1-1.html), using the Google Translate button that appears on that page, letting that translate the content, and then running Just Read does work. I recommend doing that instead.

I'm going to go ahead and close this issue since there's nothing that can be done.
