### ISSUE TITLE
Rendering xml code snippet strips xml tags

### ISSUE THREAD

**Issue by dodalovic** [ZachSaucier/Just-Read#28]
By visiting [modelmapper.org](http://modelmapper.org/getting-started/) (issue not unique to page): 

xml code snippet 

```xml
<dependency>
  <groupId>org.modelmapper</groupId>
  <artifactId>modelmapper</artifactId>
  <version>0.7.5</version>
</dependency>
```
is not rendered as it should have been:

> org.modelmapper
> modelmapper
> 0.7.5

I was expecting to see xml code snippet.

**Comment by ZachSaucier** [comment]
Good catch. I need to somehow detect the desired XML/HTML tags and replace the `<`s with `&lt;` and the `>`s with `&gt;`

**Comment by dodalovic** [comment]
Yes, I guess issue is not trivial to solve. But - there might be a lot websites where we some bunch of tech content (not only code) that should preserve formatting. 
Would be great if it can be done.

**Comment by ZachSaucier** [comment]
I made a mistake, that wasn't the problem at all. What *was* the problem is that in the default stylesheet, I have the following line:

`[class ^= "tag"], [class *= "-tag-"], [class $= "-tag"], [class $= "_tag"], [class ~= "tag"], [id ^= "tag"], [id *= "-tag-"], [id $= "-tag"], [id $= "_tag"], [id ~= "tag"], [class *= "-tags-"], [class $= "-tags"], [class $= "_tags"], [class ~= "tags"], [id *= "-tags-"], [id $= "-tags"], [id $= "_tags"], [id ~= "tags"] { display: none; }`

And since that site in particular uses `.tag` in their code, it's hiding it. As such, you can fix the problem by removing the `[class ^= "tag"]` and `[class ~= "tag"]` part of that selector.

**Comment by dodalovic** [comment]
Thank you for support.

@ZachSaucier Would it be possible to _highlight just slightly_ code snippets so that they become distinct to regular texts. I assume code snippets are special parts of texts even in _just read_ mode?

**Comment by ZachSaucier** [comment]
You can add that to your custom styling! Something like `.code { background-color: lightgrey; }` would work

**Comment by dodalovic** [comment]
Better, but each line is painted separately... I guess I expected a whole code block having single background

**Comment by ZachSaucier** [comment]
@dodalovic Check my updated post above

**Comment by dodalovic** [comment]
@ZachSaucier Cool, nice job, thank you!
