### ISSUE TITLE
Doesn't work properly with engadget

### ISSUE THREAD

**Issue by rchawda55** [ZachSaucier/Just-Read#284]
The extension doesn't work on engadget.com. link below:

[https://www.engadget.com/2019/12/03/x-ray-lasers-spot-fastest-election-motions/](https://www.engadget.com/2019/12/03/x-ray-lasers-spot-fastest-election-motions/)

**Comment by ZachSaucier** [comment]
Hello and thanks for the report.

It seems to work just fine for me. What do you mean it "doesn't work properly"?

**Comment by rchawda55** [comment]
It got too much extra content from left and bottom bars as well as sponsored content as well. I could share screenshots if it helps.

**Comment by ZachSaucier** [comment]
Just Read does its best to generically select all of the article content and hide non-related elements of the page. However it can't do a perfect job of this due to the wide nature of crap that sites put along with their articles.

Just Read does its job of selecting all of the article content on this page, but some extra stuff is also selected. You can [delete those parts](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-delete-parts-of-the-page-once-just-read-has-started) using deletion mode. Or you could look at the HTML for those elements and hide them via your custom stylesheet. 

For example, the first part with related articles Just Read correctly marks as an aside. However asides sometimes have relevant content in them to the article so Just Read can't generically delete them. You can add that rule to your stylesheet if you'd like to. 

It's impossible for Just Read to generically do a perfect job, especially on a page like that which has terrible semantics and overall structure. Closing this as such.
