### ISSUE TITLE
Any chance to support embedded twits?

### ISSUE THREAD

**Issue by Francesco270** [ZachSaucier/Just-Read#286]
Hi, are there any chance that you support embedded tweets? They are parts of an article, not something useless. 
Also, articles from the website everyeye.it don't work correctly with Just Read, maybe you an fix it.
Thank you.

**Comment by ZachSaucier** [comment]
Hey Francesco and thanks for the report.

Can you please provide an example URL where a Twitter post is part of the content so that I know exactly what you're talking about?

And what do you mean articles on everyeye.it "don't work correctly" with Just Read? [This article](https://www.everyeye.it/articoli/recensione-hearthstone-la-discesa-draghi-nuova-espansione-46659.html) seems to work fine for me.

**Comment by Francesco270** [comment]
Hi, thank you for your reply. 
1) Sometimes a Tweet is the source of an article. For example: A famous actor says on Twitter that he will play a part in the film X. Another [example](https://www.buzzfeed.com/benhenry/jk-rowling-harry-potter-tweets).
2) Before posting I've tried several articles from that website and no one worked. 
Some examples:
[Article 1](https://anime.everyeye.it/articoli/speciale-10-fumetti-comics-importanti-decennio-46554.html): 
[10 tra i fumetti e i comics più importanti del decennio.pdf](https://github.com/ZachSaucier/Just-Read/files/4000619/10.tra.i.fumetti.e.i.comics.piu.importanti.del.decennio.pdf)
It doesn't display the article at all
[Article 2](https://tech.everyeye.it/articoli/speciale-la-top-10-prodotti-tecnologici-rilevanti-decennio-46437.html): 
[La Top 10 dei Prodotti Tecnologici più Rilevanti del Decennio.pdf](https://github.com/ZachSaucier/Just-Read/files/4000620/La.Top.10.dei.Prodotti.Tecnologici.piu.Rilevanti.del.Decennio.pdf)
Same thing
[Article 3](https://www.everyeye.it/notizie/origini-death-stranding-hideo-kojima-mostra-concept-prototipo-418685.html) 
[Origini di Death Stranding_ Hideo Kojima mostra i concept del prototipo iniziale.pdf](https://github.com/ZachSaucier/Just-Read/files/4000623/Origini.di.Death.Stranding_.Hideo.Kojima.mostra.i.concept.del.prototipo.iniziale.pdf)
Here it displays lots of useless stuff.

The article you posted works almost completely (it doesn't display the conclusions - those at the bottom displayed in blue in, after "HEARTHSTONE LA DISCESA DEI DRAGHI"). 

Merry Christmas too!

**Comment by ZachSaucier** [comment]
Reply to 1: Ya, that "article" isn't really an article. It's just a thread of posts and doesn't really fit the purpose of Just Read.

Rely to 2: I see what you mean. Sometimes you need to use Just Read's "user selection mode" to select the correct content because sometimes Just Read's auto selection fails to select the content. You can start it by right clicking the Just Read icon and then clicking on the content that you want to read. 

As such there's really not much for me to do here so I'm closing this issue.

**Comment by Francesco270** [comment]
I get what you mean. Yeah, that "article" was bs (I was looking for an article in English about the Rowling tweet as an example but I only got results in Italian and that one was the only in English). I do still think that it would be useful in Just Read to see embedded Tweets, as they are often the source of an article (lots of announcements are made by official accounts on Twitter).

Anyway, I appreciate your reply, Happy Holidays!
