### ISSUE TITLE
doesnt work on site, no text shown.

### ISSUE THREAD

**Issue by trogfield** [ZachSaucier/Just-Read#291]
this is the website

https://www.thesun.co.uk/news/10041812/concorde-crash-tiny-deadly-mistakes/

**Comment by ZachSaucier** [comment]
Hey trogfield. This is because Just Read tries to hide superfluous content like navigation. This page has a class of "has-section-nav" on a container of the content, which Just Read hides. You can fix it by disabling the "Use hide-segments.css" checkbox, by adding `.main-content-wrap { display: block; }` to your stylesheet, or by using Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content.

**Comment by trogfield** [comment]
ok, thanks!!!
