### ISSUE TITLE
Install in Microsoft Edge (Chromium)

### ISSUE THREAD

**Issue by billmcaninch** [ZachSaucier/Just-Read#292]
About a year ago I subscribed to Just Read Premium in the Brave browser which is based on Chromium. Now I wish to use it in the new Microsoft Edge which is also Chromium, however, it is not automatically appearing. How do I install in Edge?

**Comment by ZachSaucier** [comment]
Hey Bill. I haven't had the time to migrate Just Read to the new Edge yet. I plan to get to is this week sometime. I'll update you when it's been ported over!

**Comment by billmcaninch** [comment]
Thank you.

**Comment by ZachSaucier** [comment]
Edge's "Partner Center" management platform for extensions is horrid at the moment but that's a separate issue.

I'm not sure if it's possible to sync Edge's UID with Chrome's so that a user can see and manage the shared pages created in both browsers via their dashboard. I kinda doubt that it is possible to sync them - it's probably going to be something where users have some shared pages on Edge and some in Chrome if they use both. 

I'll give it a few days to see if I get a response and update you. In the mean time, I believe that you can just download JRP from Chrome's webstore in Edge: https://chrome.google.com/webstore/detail/just-read-premium/dpamdgmnffodphoamchpmbclkpmccjga/reviews The shared pages are not currently synced between the two browsers, as mentioned above.

**Comment by billmcaninch** [comment]
Thanks, just added and as you said, no sync but that's OK for me.

**Comment by ZachSaucier** [comment]
Looks like there's no way to sync the user IDs 🙁At least it works in Edge, hah.

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser including Edge 🥳 
Please let me know if you run into any issues.
