### ISSUE TITLE
Improve post date recognition

### ISSUE THREAD

**Issue by ErinPo** [ZachSaucier/Just-Read#295]
Just Read presently does a poor job of detecting the correct date from an article. It often picks dates or just times from related posts teasers or even calendar plugin teasers located in a sidebar or below the content. It does so even when the real article date is semantically formatted within the post div, say, in a class="datePublished".

Example URL:
[https://edition.cnn.com/travel/article/post-brexit-travel-advice/index.html](https://edition.cnn.com/travel/article/post-brexit-travel-advice/index.html)

I tried viewing the same pages where Just Reader fails in Safari reader mode and Chrome mercury reader and they always get it right. Maybe you can copy what they are doing for your plugin.

Mercury reader even manages do standardize the formatting of the date from the different ways pages supply the date, which is a nice touch.

**Comment by ErinPo** [comment]
Actually I just saw that Mercury Readers underlying engine has been open sourced so maybe you could use it for your plugin.

`https://github.com/postlight/mercury-parser`

**Comment by ZachSaucier** [comment]
Mercury Reader's underlying engine has been open source for a while. I'm not going to switch over to using their engine because it'd add a significant amount of size to my project and I don't think JR needs it at this point.

I improved JR's ability to find dates and times if they follow the schema used on that page. It'll be in the next release.

P.S. JR already had logic for things like `class="datePublished"` in place. The site you linked to doesn't use that.
