### ISSUE TITLE
Free download link broken

### ISSUE THREAD

**Issue by miesismore** [ZachSaucier/Just-Read#298]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey miesismore and thanks for reaching out. So sorry about this.

This is because the web store is not allowing me to publish updates at this time due to some "review". I'm so sorry about the delay - I'm just waiting on Google at this point. I will update you when the issue has been fixed.

In the mean time, if you want to run the latest, working version of Just Read locally I provide [instructions on how to do so](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-run-just-read-from-a-local-copy-on-my-computer) (last entry in the FAQ). I recommend switching back to the web store version once this issue has been resolved though.

For more information and updates about the issue, check #297.

Sorry again for the trouble.

**Comment by miesismore** [comment]
Did this yesterday but today i have no extension... :/
Thank you,

**Comment by ZachSaucier** [comment]
> Did this yesterday but today i have no extension... :/

What do you mean? It's not visible when you go to chrome://extensions/?

**Comment by miesismore** [comment]
Yes, it isn't. Going to install again and let's see tomorrow... :)

**Comment by ZachSaucier** [comment]
My guess is that either you or some security program deleted the file then. I've never heard of that happening.

**Comment by miesismore** [comment]
Installed, had this error:
![CAPT-0000](https://user-images.githubusercontent.com/28994304/74869657-a0e7e180-5358-11ea-8600-e9147f714a66.png)

**Comment by ZachSaucier** [comment]
You can delete that. It's for Firefox. Not sure why it's throwing an error for you though.

**Comment by miesismore** [comment]
Thank you Zach, the "problem" is that when restarting Chrome i am asked to "disable" develop mode extensions, so yesterday i suppose i did click and disable. 
Best regards,

**Comment by fireton** [comment]
After 20 days Just Read Free still not published... It is always takes so long?

**Comment by ZachSaucier** [comment]
> After 20 days Just Read Free still not published... It is always takes so long?

It usually only takes a day or two. But they provide zero information about why is being reviewed and the status of the review. They also provide no way to cancel it. And there's no way to get in contact with anyone related to the process. So there's literally nothing I can do. It's quite terrible.

**Comment by fireton** [comment]
So much for «do no harm» principle...

**Comment by ZachSaucier** [comment]
Just Read is finally back online now.
