### ISSUE TITLE
Use styleable SVGs for the print/close icons

### ISSUE THREAD

**Issue by dflock** [ZachSaucier/Just-Read#3]
This would enable you to change the color of the icons in your styles - for example, when creating a dark theme.

Currently if you create a dark theme, the print icon will become invisible against the dark background.

**Comment by ZachSaucier** [comment]
Hello dflock, thanks for the useful contribution! I originally thought about this for the closing X button but didn't when I added the print functionality.

I [just changed](https://github.com/ZachSaucier/Just-Read/commit/c546cffbcb4779a860b861cf83fb1fffab7ef3b4) the background image from a PNG to an SVG obtained from [this page](http://www.flaticon.com/free-icon/printer_132964). You can style it using the `.simple-print` class. To change the outline color, you can use [CSS's filter functions](https://developer.mozilla.org/en-US/docs/Web/CSS/filter), e.x. `-webkit-filter: invert(100%);` to make it white. 

I realize that this isn't very freeing in terms of styling, but I don't believe that it needs to be. Leaving it as a background image allows me to change it more easily later and keeps the markup-style separation.

**Comment by ZachSaucier** [comment]
**Update:** I have now inlined the print SVG icon because I needed to implement the functionality for a potential new feature. The new changes (available in a56b275 / 0.0.31) are as follows:

- A `.simple-control` class has been added to the print and close buttons
- The print icon can be styled using the `fill` property and, for desired thickness, the `stroke` property of `.simple-print`
- All `.simple-control`s by default use a change in opacity on hover, not color. This, as with all styling in the extension, can be changed if desired

I hope that allow more freedom!

Cheers
