### ISSUE TITLE
Sidenotes in wrong position in shared pages

### ISSUE THREAD

**Issue by Yaco** [ZachSaucier/Just-Read#307]
**Describe the bug**
When you share a link of an article (using JustRead Premium) the sidenotes are in a different place than original JustRead article (the one you can highlight and and comments). The sidenotes are moved down one line. 

I think that this error is generated because there is an extra line, in shared articles, on top of the main title that is added to go to the source article. The line is "View original page". This seems to shift the position of all elements below it.

Comparision images:

Original / Editable page:
![image](https://user-images.githubusercontent.com/139963/78987457-79192c80-7b04-11ea-8f8b-ff00e2a2b538.png)

Shared page:
![image](https://user-images.githubusercontent.com/139963/78987514-9e0d9f80-7b04-11ea-97ed-e4255f329d05.png)

**Comment by ZachSaucier** [comment]
Good catch. This lead me to find that some authors were missing from the shared pages due to a recent change 🙂

Both should be fixed now. However, part of the fix may only apply to pages shared from now on (once you're on the newer version of JRP - 4.2.7), so some shared pages made in the past may have a slight offset. Sorry about that.
