### ISSUE TITLE
Content that's not part of the article is being added to Just Read's selection

### ISSUE THREAD

**Issue by SpiderJonny** [ZachSaucier/Just-Read#319]
1. Go to https://www.tabletmag.com/sections/arts-letters/articles/physics-secular-religion
2. Activate Just Read
3. A large number of images and links that are not on the original page are now rendered above the main content, which is now about 90% of the way down a very long page.  (They relate to articles that are in the sections linked from the bottom of the original page, but none of the images or links appear on the page itself.)

Expected behaviour:

I would just expect the main text content (plus associated inline images) to be rendered. 

 - Windows 8.1
 - Chrome
 - Version 83

Thanks.

**Comment by ZachSaucier** [comment]
Hey Jonny. Those images are in the navigation of the page which is being pulled in because apparently the article's main content doesn't meet the threshold of the number of paragraphs compared to the total number of paragraphs on the page. In other words, the page's markup is not very good if you ask me 🙂 

In situations like this I highly recommend using Just Read's [use selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content yourself.

**Comment by SpiderJonny** [comment]
_> Hey Jonny.  In other words, the page's markup is not very good if you ask me_ 

Thanks for the speedy reply.

I did have a look at the source, and suspected it was all SEO stuff that was messing things up.

_> In situations like this I highly recommend using Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content yourself._

Thanks. I don't know why, but I always forget about that option - sorry.

And thanks for much-improving my original title.

**Comment by dave-linsalata** [comment]
This may be a separate issue, but it has hints of the above.

In https://www.nytimes.com/2020/06/30/science/how-coronavirus-spreads.html, Just read pulls up the FAQ that is embedded part of the way down, but doesn't show anything of the actual article itself.

**Comment by ZachSaucier** [comment]
@dave-linsalata It seems to work fine for me.

**Comment by ZachSaucier** [comment]
Merging this into #331 which is a larger issue that contains this issue.
