### ISSUE TITLE
Only a section of the page renders in the Just Read format

### ISSUE THREAD

**Issue by tjterris** [ZachSaucier/Just-Read#32]
on https://www.privateinternetaccess.com/pages/downloads the first section is correctly rendered, but none of the following, but identically formatted sections render

**Comment by ZachSaucier** [comment]
Thanks for the report! It's because each section is technically in their own container, so Just Read selects the first container. I'll still working to try and fix this in the auto-selection mode, but I'm not sure how I can do that without error across all sites.

However, have you tried out [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) or highlight mode? I was able to easily get all the content using both of those modes.

**Comment by paulvancotthem** [comment]
I have a similar issue on pages in the "motorsport.com" domain.
Example:
[http://www.motorsport.com/f1/news/massa-returns-to-f1-as-bottas-replacement-865853/](url)

**Comment by ZachSaucier** [comment]
@paulvancotthem That website seems to work when I use JR's auto-selection..

**Comment by paulvancotthem** [comment]
@ZachSaucier It does not fully work for me. The top H1-title of that article ("_Mercedes confirms Bottas as Hamilton's teammate_") and the photo at the top of the page do not show up after JR parses it. JR's output starts with the H2-subtitle.

**Comment by ZachSaucier** [comment]
@paulvancotthem I understand now. The title isn't obtained because JR checks the article's container for a h1 or h2 first, then more globally (I believe that this approach is generally more favorable - keep in mind you can manually edit the title if you need to by clicking the pencil after hovering the title). The photo is just outside the article container, so it would be hard to programmatically find images like that and determine whether or not they should be included.

**Comment by paulvancotthem** [comment]
@ZachSaucier When I use the "_**Clearly**_"-extension (from Evernotes; no longer supported, but still available for download [**here**](https://www.crx4chrome.com/crx/625/)), it renders this page correctly, both the title and the image and the rest of the article are parsed and rendered correctly. So, there must be a way to do this programmatically...
![screenshot-001](https://cloud.githubusercontent.com/assets/18426742/22152779/ad3272d0-df24-11e6-9e4f-0ede88bccc44.png)

**Comment by ZachSaucier** [comment]
I seem unable to get that download of Clearly to work on my computer. I can look at the code though, so I'll try to break down what's going on to let them select better than how JR selects.

**Comment by paulvancotthem** [comment]
@ZachSaucier Oh wow, thanks Zach!

**Comment by ZachSaucier** [comment]
For future reference for myself, a running list of other sites with this same issue:

- http://www.catb.org/esr/faqs/things-every-hacker-once-knew/

**Comment by ZachSaucier** [comment]
One idea I have (potential feature) to help, not solve this, is to implement a "select more generally" or "select parent container" button. That way, if only part of the content is shown, users can stay in the Just Read format but select more content (which should tend to be the full article).

**Comment by iandunn** [comment]
> each section is technically in their own container, so Just Read selects the first container... I'm not sure how I can do that without error across all sites.

You may have already considered this, but would it be a problem to just include all the `<article>` elements inside the container?

Maybe some sites put too much crap in there, but with all the other formatting stripped away, it doesn't seem like it'd be that bad. At least for me, having too much (clean) text is a minor problem, while missing some important text is a major problem.

**Comment by ZachSaucier** [comment]
@iandunn The main problem using that approach is that I've come across sites that don't use the article content for the article at all, they use it only for previews of other articles (why they do so eludes all logical explanations I can fathom).

This is really just a symptom of the larger problem of how JR does auto-selection. If I have time I'll look at redoing all of it this summer, but time gets shorter every day, haha.

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.
