### ISSUE TITLE
I could not read content with Just-Read on this website: spiderum.com

### ISSUE THREAD

**Issue by liwenjing93** [ZachSaucier/Just-Read#320]
Dear everyone, 

All links from this website can not read by Just-Read. Can you check it out? eg: https://spiderum.com/bai-dang/Neu-la-gian-hay-la-gian-sao-phai-lam-thien-nga-pup

Thank you!!!

**Comment by ZachSaucier** [comment]
Hey liwenjing and thanks for posting. It looks like a comment is being selected instead of the article content? In that case it's a duplicate of #94. 


You can use [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to read article's content where JR fails to select the correct content.

**Comment by liwenjing93** [comment]
Dear @ZachSaucier , Thank you for your help.
