### ISSUE TITLE
Navigation links not loaded on webnovel sites

### ISSUE THREAD

**Issue by inhaspie** [ZachSaucier/Just-Read#322]
> **Describe the bug**
On multiple webnovel sites the next/previous chapter links are not loaded into just read's reader view. On wuxiaworld.com they are loaded however on fastnovel.net, wuxiaworld.co, royalroad.com and even webnovel.com they are not.

**To Reproduce**
1. Go to 'https://fastnovel.net/lord-of-the-mysteries1-19/chapter-20577.html (or any of above mentioned sites)'
2. Click on/enable 'just read'
3. Scroll down to 'bottom'

**Expected behavior**
I would like for the chapter navigation buttons/links to show up. In the reader view/mode.

 - OS: [Windows 10]
 - Browser [chrome]
 - Version [2.2.7]

**Comment by ZachSaucier** [comment]
Hey inhaspie and thanks for posting. This isn't a bad suggestion, though it's definitely not a "bug" given next chapter buttons are not *really* in the scope of Just Read. 

With that being said it may make sense to support the most common online book sites. I'm not really familiar with these types of sites - are all of these sites widely used? Are there any others that you didn't list that aren't supported? 

Also on https://www.webnovel.com/ it seems to load the content in one continuous scroll instead of separate pages. Is there any way to switch to a paginated system on that site? Just Read can't dynamically load content.

**Comment by inhaspie** [comment]
Let me start by thanking you for the fast response. The enhancement tag is indeed more suitable. As far as https://www.webnovel.com/ that was a mistake on my part there's no need to fix that, safari's reader mode does work with continous scrolling though.
The sites I listed are the ones I know of. One other site I found by a quick google search is https://www.lightnovelworld.com/ same situation there. 
I would be very grateful if you can implement the navigation buttons into reader view.

**Comment by ZachSaucier** [comment]
I came up with a way to add the next chapter button on all of the sites that you linked to. It also adds a class of `jrNextChapter` to the link if it's added by Just Read. I submitted the new versions to the webstore just now.

In case you're not aware, Just Read's auto-run feature would be helpful on sites like this. You can learn more about it under "How can I auto-run Just Read on specific websites?" in the [JR FAQ](https://github.com/ZachSaucier/Just-Read).
