### ISSUE TITLE
Author not found on Macworld.com; shows "Unknown author"

### ISSUE THREAD

**Issue by jimratliff** [ZachSaucier/Just-Read#323]
The following article at MacWorld.com: https://www.macworld.com/article/3571181/how-filevault-and-the-t2-security-chip-work-together-in-newer-macs.html

clearly has a byline saying "By Glenn Fleishman". Just Read however shows "Unknown author".

I note that Mercury Reader *does* parse the author name correctly.

**Comment by ZachSaucier** [comment]
Hey Jim and thanks for posting. 

The issue is because the site has multiple elements with rel='author' and the first one in the page has only an image of the author in it. In the next version of Just Read I loop through _all_ elements with rel='author' to check for the name so this should be fixed.

I'll upload a new version to the webstore soon.
