### ISSUE TITLE
northwestern.edu page does not respond to extension

### ISSUE THREAD

**Issue by tbc** [ZachSaucier/Just-Read#330]
**Describe the bug**

**To Reproduce**
1. Go to https://www.northwestern.edu/leadership-notes/2020/weekend-protests-in-evanston.html
2. Try to make the page respond to Just-Read

**Expected behavior**
Just-Read to change the display for easy reading

 - OS: Windows 10
 - Browser firefox
 - Version 81.0.2

**Comment by ZachSaucier** [comment]
Hey tbc. Very interesting. This site has the following style rule:

```
footer ~ iframe { display: none !important; }
```

So since Just Read uses an iframe and appends it to the end of the page, the rule above hides the Just Read view.

If you read on this webpage regularly you can add a custom CSS rule to override this style:

```
#simple-article {
    display: block !important;
}
```

If you don't read from this website regularly, I recommend that you just leave it as is 🙂 It's not worth me adding a workaround in the CSS of Just Read for this case I don't think.
