### ISSUE TITLE
PURCHASED Premium. Will NOT Install to Brave.  Help PLEASE!!

### ISSUE THREAD

**Issue by Chuck-7** [ZachSaucier/Just-Read#334]
PURCHASED Premium for Brave Browser. 
The Install Fails: When it attempts to Download, the Error Message Pops Up:: "**"Failed—Needs Authorization"**".

Perhaps I could get the correct download from your Page .. OR install it MANUALLY?

Would Greatly Appreciate Your Help!  THANKS,
Chuck Colsch

**Comment by ZachSaucier** [comment]
Hey Chuck, thanks for reaching out.

It looks like something is wrong with Brave's installation of paid extensions at the moment. Sorry, I don't have control over that so I can't help you there. 

I'm currently in development of a new version of Just Read where it is free to install (for everyone) and then you sign into Just Read itself to enable premium features. I hope to have it released in the next 3-5 weeks. Until that time, I recommend using Just Read Premium in Chrome. 

If you're not willing to do that, I'm happy to refund your purchase. Just send your receipt to support@justread.link. Let me know if you have any questions 🙂

**Comment by Chuck-7** [comment]
Thanks for your reply —
Yeah, I **Hate** Chrome (though I have it installed), so constantly Switching Browsers obviously is not an option!!
_And as far as I can tell, BRAVE is the ONLY Quality Browser with the correct view of Auto-Blocking Ads & Trackers (“Opera” works similarly but is lacking in TOO many features);  While Chrome takes the **Opposite** Approach to Ads & Trackers!!_

SOO, if I understand you correctly, I will retain my Premium Status (_With Zero Features_);;   Then, after a few weeks, I can just Sign In somewhere And it will Automatically KNOW to give me the Premium Features – –AND it will work Just FINE with Brave.  Is that Accurate??

Thank You,
_Chuck Colsch_

**Comment by ZachSaucier** [comment]
> after a few weeks, I can just Sign In somewhere And it will Automatically KNOW to give me the Premium Features – –AND it will work Just FINE with Brave. Is that Accurate??

I recommend installing the free version on Brave for now. It should install fine. Then in a few weeks the free version will be updated and you should see the premium features appear. However, the premium features will not work until you sign in - there will be a link to sign in. 

The whole reason I have to make this new version is because Chrome's payment functionality is being deprecated. So the new version will have a separate payment system. I plan on setting it up to where anyone with the _premium_ extension will be able to get a year in the new payment system for free (since their current year of membership hasn't expired yet). 

But since Brave is not allowing you to add the premium version, at that time I recommend that you:

- log into Chrome (one time) so that the system knows that you have already bought Premium,
- make an account and "purchase" (the system will require a payment method but there won't be a charge) the extension on the new system. 

At this point your _account_ will have access to the premium features. So you'll:

- go back to Brave, 
- sign into the account you just made, and 
- then be able to use Just Read with the premium features enabled. 

I know that's a process and I'm sorry for that. Unfortunately Google doesn't provide anyway for me to automatically migrated people to the new system, so it will take a few steps one time for people to migrate. 

Alternatively I could refund your purchase now and then when the new version comes out you could make the purchase in Brave itself. That's more simple if you'd like to do that. Do note that I am increasing the cost of the premium version from $10/year to $12/year at that point though. 

Thanks for supporting Just Read!

**Comment by Chuck-7** [comment]
Yes Please, I really NEED Simple::  IF there is ANY way to Screw Something Up, I Usually take that route, and then can’t figure out what THE HECK happened, whereupon I would contact you, and you’d have to straighten out this dummy.

SOO, if you could please process that refund that would be GREAT!!  THANKS!!

**Comment by ZachSaucier** [comment]
Sure thing. Please forward the receipt from the Chrome store to support@justread.link and I'll do that right away.

**Comment by Chuck-7** [comment]
Okay, I Forwarded it. 
Let me know if you have any more suggestions!
THANK YOU AGAIN!

**Comment by ZachSaucier** [comment]
Happy to help!

**Comment by ZachSaucier** [comment]
The newest version of Just Read (v 5.0) now supports Premium features in every browser including Brave 🥳 
Please let me know if you run into any issues.
