### ISSUE TITLE
Premium Features Not Working

### ISSUE THREAD

**Issue by laflier** [ZachSaucier/Just-Read#340]
Tried 5.0.3. Cleared all cookies, files, and history for 24 hrs. Restarted Chrome. Still seeing this:

<img width="952" alt="Screen Shot 2020-11-27 at 2 37 09 PM" src="https://user-images.githubusercontent.com/7854264/100480138-61f07480-30be-11eb-8435-3d80a5d92ab7.png">
<img width="411" alt="Screen Shot 2020-11-27 at 2 36 16 PM" src="https://user-images.githubusercontent.com/7854264/100480153-6d43a000-30be-11eb-8e70-67d966c5e0e6.png">

**Comment by ZachSaucier** [comment]
Did you make sure to log in again?

**Comment by laflier** [comment]
Yes. Cleared cookies again. Logged out. Re-authenticated. Logged in. Same result as above.

**Comment by ZachSaucier** [comment]
Hmm. I'm out right now but I'll investigate more later tonight. Sorry for the troubles.

**Comment by laflier** [comment]
Am I perhaps missing the necessary cookie? Here's a list of cookies currently in Chrome. FWIW the doubleverify cookie appears to be empty.

<img width="499" alt="Screen Shot 2020-11-27 at 2 55 49 PM" src="https://user-images.githubusercontent.com/7854264/100480947-b7c61c00-30c0-11eb-951c-2cf773ac9fb4.png">

**Comment by ZachSaucier** [comment]
If you go to [the Just Read dashboard](https://justread.link/dashboard) you should see a thank you and a table for shared pages (whether or not that table has entries depends on whether or not you've shared pages before). The page's display varies depending on your user state which is saved in a cookie. If it is displaying a "thank you" and the table, the cookie is being set properly. If it's not set, please let me know.

Assuming it is set correctly, open Just Read and try using a Premium feature. If it doesn't work, that means that there's some issue between the website and the extension. 

To try and figure out what the issue is, here are things we can try:

- Before starting Just Read, open up the console by pressing F12. Then open Just Read and try a Premium feature. Do any errors appear?
- Open up Just Read's options page. Does it say "Thanks for supporing Just Read!" at the top? I just realized there's a misspelling there so I'll fix that.
- Try clearing your cookies for Just Read again. FYI in Chrome if you go to the Just Read website you can click the lock icon next to the URL and then click "Cookies" -> "justread.link" to see them. You just need to delete the `refreshToken` cookie. I might add a "sign out button" that does this soon. Then open up the console (F12), log in, and then see if there are any errors in the console when it returns back to the Just Read website.

I'm not seeing any errors on the server side.

Sorry again for the trouble. Thanks for being patient and working with me.

**Comment by JoaoPauloAlexandre** [comment]
@laflier, when in the dashboard, disable AdGuard and try again. That was the issue for me, using Brave, which is a chromium based browser.

**Comment by ZachSaucier** [comment]
I also made a change to the Just Read server that causes the tokens to get flushed when you log in again. So perhaps logging in again will fix it.

**Comment by laflier** [comment]
Hey, it's working now! Congrats!
