### ISSUE TITLE
Doesn't show a share icon if Adblock Plus `Block social media icons tracking` is on

### ISSUE THREAD

**Issue by sviatoslav-lebediev** [ZachSaucier/Just-Read#348]
When Adblock Plus `Block social media icons tracking` is on Just Read doesn't show a share icon

1. Install Adblock Plus https://adblockplus.org/
2. Go to Options/General, enable `Block social media icons tracking`
3. Open any web page and in Just Read
4. The share icon is absent
5. Disable `Block social media icons tracking`
6. Reopen the page
7. The share icon is visible

AdBlock Plus options
![image](https://user-images.githubusercontent.com/19693768/101984872-d6194380-3c8c-11eb-9dab-34ad7cfd3392.png)

Result
![image](https://user-images.githubusercontent.com/19693768/101984855-a79b6880-3c8c-11eb-8e2c-4c840ebd67c9.png)

p.s. Thank for the extension :)

**Comment by ZachSaucier** [comment]
Hey sviatoslav. I don't understand how this is an error with Just Read. It is clearly your other extension interfering.

With that being said, I recommend you use something like uBlock Origin instead of Adblock Plus if you're going to use an ad blocker. It's open source and doesn't have its own agenda.

**Comment by sviatoslav-lebediev** [comment]
Hi, I'm not saying that's a huge bug :) But maybe you can find a way to fix it. I've bought a premium version and couldn't understand why I don't have a share icon.
