### ISSUE TITLE
Double(repeated) Pictures on New York times. And sometimes double headlines. 

### ISSUE THREAD

**Issue by jasonbourne27** [ZachSaucier/Just-Read#368]
Double(repeated) Pictures on New York times. And sometimes double headlines. 

<img width="801" alt="Screen Shot 2021-05-04 at 1 19 37 PM" src="https://user-images.githubusercontent.com/59314872/117043573-66f3c880-acdb-11eb-921d-f13738bf0029.png">

<img width="1160" alt="Screen Shot 2021-05-04 at 1 22 59 PM" src="https://user-images.githubusercontent.com/59314872/117044649-aec71f80-acdc-11eb-873f-5e678e277afd.png">

MACOS - Big Sur, Chrome browser

This also happens for images. Is there an option or code that could prevent this from happening?

Thank you for all your hard work and for the beautiful extension!

**Comment by jasonbourne27** [comment]
<img width="1160" alt="Screen Shot 2021-05-04 at 1 22 59 PM" src="https://user-images.githubusercontent.com/59314872/117043993-e4b7d400-acdb-11eb-9e0b-5a7c60a7caf3.png">

Another example of this.

**Comment by ZachSaucier** [comment]
Hey jasonbourne27. 

The reason for the images being repeated is because the images are repeated on the NYT website. They are duplicated on the NYT website because you can click the image to expand it.

To hide this you could add the following style to your stylesheet:

```
[data-testid="photoviewer-overlay"] { display: none; }
```

But if they change their markup this wont work... That's why adding rules like this for specific sites is pretty out of the scope of the functionality of Just Read. But doing it yourself should work 🙂 

As for the duplicated heading, if Just Read gets the title from the content itself then it will remove the title from the content. But if it gets the title from somewhere else this removal doesn't happen (because it's not easy to detect the duplication without removing other things incorrectly). I recommend that you use Just Read's deletion mode to delete the duplicate title if necessary.
