### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by maxyor6040** [ZachSaucier/Just-Read#37]
RTL text is LTR

**Comment by ZachSaucier** [comment]
Hello maxyor,

Could you please provide a link to an example where this behavior doesn't work as you expect it to?

**Comment by ZachSaucier** [comment]
I uploaded a fix in version 1.0.17 which makes the main content support the `direction` specified in the original page's `body`, which seems to be done in every RTL page I've checked so far, though it might not always be the case.

I didn't apply RTL to the meta information (date, author, etc) because that'd add a little complexity to the project. Let me know if you think it's important enough to write a more complex fix for or if this format is satisfactory.

**Comment by maxyor6040** [comment]
Wow that was fast. Bug fixed for me. Thanks.

**Comment by ZachSaucier** [comment]
I went ahead and moved the title, date, and author into something that looks better in RTL as well. So now it should look better and the edit metadata edit functionality should work better.

**Comment by ZachSaucier** [comment]
This has since been updated (due to #116) to check the first child of the selected content for any RTL characters. If one is found, RTL for JR is also set.
