### ISSUE TITLE
Last text modification performed before closing JR isn't saved; NO comments are saved

### ISSUE THREAD

**Issue by jons-own-stuff** [ZachSaucier/Just-Read#373]
Howdy. Just upgraded to premium and I'm having an annoying issue. I searched in the open/closed issues and it's not in the FAQ. 

The last text that I modify (highlight, B/I/U, etc) isn't getting saved. It's pretty weird so I'll just run through a couple tests I've done. 

Case A
1. Highlight something
2. Either click the JR icon twice --OR-- reload the page and click the JR icon
3. Highlight is not saved

Case B
1. Highlight something
2. Highlight another thing
3. Either click the JR icon twice --OR-- reload the page and click the JR icon
4. The FIRST highlight is saved. The second is not.

Case C
1. Make one or more comments
2. Either click the JR icon twice --OR-- reload the page and click the JR icon
3. No comments are saved (yep, I've lost all my comments. sadface.)

Case D
1. Make any number of comments
2. Modify text however is needed
3. Share it and load it from dashboard
4. All changes are there as expected

I have Chrome network logs that I can provide if needed. Didn't seem to provide much information, though.

Also, I just wanted to tag something on at the end here. I know this sounds pedantic, but bear with me. I think it might be good to have the "Support" button on the dashboard lead first to a page that has some instructions on it. Basically, it would say to first check the FAQ, then to search for closed issues, then explain how to create a new one if nothing came up. Like I said, pedantic. But I've done some training for folks on Git and Git platforms like GitHub, and people just don't get it. Something about the UI makes them freeze up. They're used to a big, happy button that says, "annoy support team." I had one team member refuse to log into Azure DevOps because he was afraid of merging code to master accidentally.

**Comment by ZachSaucier** [comment]
Hey jons-own-stuff. Thanks for posting and for supporting Just Read!

I'll look into the issue of the most recent highlight not getting saved when Just Read is closed. With that being said, there are some edits that are too difficult for Just Read to properly save between being open/closed. That may or may not be related to the issue here; it kinda sounds like it's not related but I wanted to be transparent 🙂 

> I think it might be good to have the "Support" button on the dashboard lead first to a page that has some instructions on it. Basically, it would say to first check the FAQ, then to search for closed issues, then explain how to create a new one if nothing came up.

I think this is a pretty good suggestion! When I have to do some maintenance for the Just Read server sometime soon so I'll add this to the todo list also.

**Comment by jons-own-stuff** [comment]
Thanks for the speedy response! Seems that I've found another issue. I can't seem to clear formatting anymore. If I make a change, it's permanent. And because I wanted to use "backup the most recent page," it seems the only way to start over is to undo that, reload, and reset it. Is there a manual reset? It's still not optimal, obviously... any accidental changes are permanent.

**Comment by ZachSaucier** [comment]
> I can't seem to clear formatting anymore. If I make a change, it's permanent.

Hmm. Something sounds like it has broken. Are there relevant errors in the developer console (F12 to view)?

**Comment by ZachSaucier** [comment]
Case A and B were a bug but I believe is should be fixed in the most recent version.

Case C was not supported, but I added support for it so it should work now.

I also created a support page which you can view at https://justread.link/support/. Let me know if you have other suggestions for improvement 🙂

**Comment by albertcb98** [comment]
Hi There, congrats for solving the other issue, it's awesome :)

Im having a small issue but that can be a bit dangerous:
Nothing happens when Im editing a comment and click cancel (shown at the end of video) or the cross (not shown on the video)  **but if I click on the side all (shown at min: 0:05 and 0:50) * the existing comments disappear**  . check the video bellow: 

https://user-images.githubusercontent.com/44147495/128983099-5f33aff1-02f8-4505-9d3f-d31de08119a0.mp4


Even though this issue I wanted to thank you for the cool extension, 
Albert

**Comment by ZachSaucier** [comment]
Ooh, that is an issue. Sorry for those lost comments. Thanks again for reporting the issue!

I'll investigate this issue when I get some time. I've gone ahead and created a new thread about it linked above.

**Comment by albertcb98** [comment]
Awesome brother, Fixed! 😄
