### ISSUE TITLE
article shows huge triangles beneath each image

### ISSUE THREAD

**Issue by pidloop** [ZachSaucier/Just-Read#380]
**Describe the bug**
Each image in this article has a huge gray triangle beneath it.

**To Reproduce**
1. Go to 'https://www.theguardian.com/lifeandstyle/2021/sep/13/what-i-learned-from-living-five-years-in-a-van'
2. Scroll down to any image
3. See error

**Expected behavior**
No triangles.

**Screenshots**
Typical example attached.

**Please complete the following information:**
 - OS: macOS 11.5.2
 - Browser chrome
 - Version 93.0.4577.63 (Official Build) (x86_64)

**Additional context**
First I've seen this, normally works very well. Thanks.

<img width="1872" alt="Screen Shot 2021-09-15 at 14 27 42" src="https://user-images.githubusercontent.com/12057700/133512151-a28b2ff7-8c66-43f5-b1f4-4edcfc218263.png">

**Comment by ZachSaucier** [comment]
Hey pidloop and thanks for posting.

That is because they use an SVG as a part of their markup. Just Read [attempts to resize icons and such](https://github.com/ZachSaucier/Just-Read/blob/master/default-styles.css#L167) but unfortunately The Guardian also obfuscates all of its class names and such, which makes selecting things like that generically kind of a nightmare... 

I recommend that if you read The Guardian regularly you modify your personal stylesheet to be the following:

```
/* Make emojis and icons a reasonable size */
[class *= "emoji"],
figcaption svg,
[class *= "icon"]:not([class *= "no-icon"]) { width: 1em; }
[class *= "inline"] { display: inline-block; min-width: 2rem; }
```

If you don't read The Guardian regularly, maybe just use Just Read's [deletion mode](https://github.com/ZachSaucier/Just-Read#user-content-deletion_mode) to get rid of it when needed.

**Comment by pidloop** [comment]
Thanks for the quick reply Zach. The Configure code had almost this
already, except for the figcaption line. I made the change and now it's
even worse, with several more gigantic black shapes here and there. Sounds
like a difficult problem in general so I can live with it, still lots
better than nothing. I just discovered Just Read a few days ago and already
I use it often. Many thanks to all involved.

**Comment by ZachSaucier** [comment]
I'm glad to hear you're liking it so far! Let me know if I can help with anything else.

**Comment by pidloop** [comment]
Hi Zach,

Just wanted to share with you that I ran across an undocumented
experimental feature in chrome 93 that I turned on by entering
*chrome://flags/#enable-reader-mode* in the search bar. I'm not trying to
rub it in, just wanted to share with you, but it works better than your
extension, even on Guardian it makes the page very clean and easy to read.
I don't know how either works, there must be a lot of html magic under the
hood, so I'm impressed it can be done at all.

Anyway, best wishes.

Elwood Downey
Tucson AZ
