### ISSUE TITLE
Zoom Upon Open

### ISSUE THREAD

**Issue by weswitt** [ZachSaucier/Just-Read#381]
i love just read but a new feature would make it even better.  i would like an option to have the page zoomed to specific zoom level when a new page is opened.  i can do ctrl+ to do this but i'd like it to be automatic.

**Comment by ZachSaucier** [comment]
Hey weswitt. Unfortunately zoom level is impossible to set programmatically as it's a user setting.

Alternatives:

- Make the font size and content width of the Just Read view larger (so you don't need to zoom)
- Share the Just Read view (Premium feature only). Since all shared pages are hosted on https://justread.link/, the zoom setting you used previously will be used.
