### ISSUE TITLE
Newlines not in html added

### ISSUE THREAD

**Issue by thuris** [ZachSaucier/Just-Read#394]
Example is from https://linux.die.net/man/1/buffer

This HTML:

`<b>buffer</b> [<b>-S size</b>] [<b>-b blocks</b>]`

(Note the square brackets are not given their own element. They belong to the large div of class "content" that fills the purpose of `<main>`.)

Should be formatted like this:
**buffer** [**-S size**] [**-b blocks**]

Just Read formats it as:
**buffer**
[
**-S size**
] [
**-b blocks**
]

**Comment by ZachSaucier** [comment]
Hey thuris and thanks for posting.

This issue is caused by [this part of Just Read's styles](https://github.com/ZachSaucier/Just-Read/blob/0a570329efb7fefad6c719004c5996122c98c5c0/required-styles.css#L30-L32) which was added to make sure that content that Just Read selects is displayed. I will investigate whether or not it is necessary through testing various pages when I get the time.

With that being said, if the markup for that website were better (like having a container HTML element around elements/text that should be on the same line, which is standard) this would not be an issue...

**Comment by ZachSaucier** [comment]
In version 5.2.0 I went ahead and removed the CSS causing this issue but no promises that it won't be added back later if I come across the need to do so 🙂
