### ISSUE TITLE
Wikihow.com page can not be rendered correctly for reading!

### ISSUE THREAD

**Issue by Abukamel** [ZachSaucier/Just-Read#40]
Hello,
Following is a screenshot
![image](https://cloud.githubusercontent.com/assets/1246960/22616500/34c9d648-eabf-11e6-8b18-d508930c81d1.png)

**Comment by ZachSaucier** [comment]
Wow, wikiHow's markup is ***terrible***. 

The main problem is that they don't use `<p>` tags (#27) but it likely also has to do with how they use containers (#32; though their structure doesn't really make sense).

I'm working on developing a new auto-selection which should hopefully fix even these problems, but until then you can use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) or [highlight mode](https://github.com/ZachSaucier/Just-Read#highlight-mode) to manually select however much of the page you need. On wikiHow, you may also need to use [deletion mode](https://github.com/ZachSaucier/Just-Read#deletion-mode) after manually selecting content because they have a bunch of extra crud along with the "article" content.
