### ISSUE TITLE
USA Today website: Doesn't work and locks up while in justread mode.

### ISSUE THREAD

**Issue by sicpupaz** [ZachSaucier/Just-Read#402]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey sicpupaz and thanks a lot for the report!

My goodness, that site is a trashfire. It brought a edge cases that Just Read didn't handle well that should be fixed in version 5.2.6 which I'm pushing to webstores now:

- It loads _sooo many_ scripts that Just Read's script loading sometimes failed to load in time. This was the main error. This was fixed by queueing the main Just Read script after the prerequisites.
- They have styles hid Just Read. This was fixed by modifying Just Read's `page.css` to try and prevent this better.
- They have styles prevented selection of content within the Just Read view. This was fixed by modifying Just Read's `page.css` to try and prevent this better.

**Comment by sicpupaz** [comment]
Agreed that website and there associated local website here in Phoenix (Arizona Republic) is a trashfire!
    On Tuesday, August 9, 2022 at 03:36:40 PM MST, Zach Saucier ***@***.***> wrote:  
 
 


Hey sicpupaz and thanks a lot for the report!

My goodness, that site is a trashfire. It brought a edge cases that Just Read didn't handle well that should be fixed in version 5.2.6 which I'm pushing to webstores now:
   
   - It loads sooo many scripts that Just Read's script loading sometimes failed to load in time. This was the main error. This was fixed by queueing the main Just Read script after the prerequisites.
   - They have styles hid Just Read. This was fixed by modifying Just Read's page.css to try and prevent this better.
   - They have styles prevented selection of content within the Just Read view. This was fixed by modifying Just Read's page.css to try and prevent this better.

**Comment by sicpupaz** [comment]
Justed tested the fix and it works perfectly. 
Great Job!
    On Wednesday, August 10, 2022 at 11:49:08 AM MST, Ron Campbell ***@***.***> wrote:  
 
  Agreed that website and there associated local website here in Phoenix (Arizona Republic) is a trashfire!
    On Tuesday, August 9, 2022 at 03:36:40 PM MST, Zach Saucier ***@***.***> wrote:  
 
 


Hey sicpupaz and thanks a lot for the report!

My goodness, that site is a trashfire. It brought a edge cases that Just Read didn't handle well that should be fixed in version 5.2.6 which I'm pushing to webstores now:
   
   - It loads sooo many scripts that Just Read's script loading sometimes failed to load in time. This was the main error. This was fixed by queueing the main Just Read script after the prerequisites.
   - They have styles hid Just Read. This was fixed by modifying Just Read's page.css to try and prevent this better.
   - They have styles prevented selection of content within the Just Read view. This was fixed by modifying Just Read's page.css to try and prevent this better.
