### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by therealmarv** [ZachSaucier/Just-Read#41]
I suggest a MIT license, what do you think?

**Comment by ZachSaucier** [comment]
Technically the license isn't missing, the default GitHub license applies to any without an explicit license:

> Code without an explicit license is protected by copyright and is by default All Rights Reserved. The person or people who wrote the code are protected as such. Any time you're using software you didn't write, licensing should be considered and abided.

I'm not willing to give it a license as freeing as the MIT license right now because I'm not sure if I'll [monetize a version of Just Read](https://github.com/ZachSaucier/Just-Read/issues/20) in the future and am not sure exactly what the implications of having a license on it right now would be if I did monetize a version of it.
