### ISSUE TITLE
Not working at Project Syndicate https://www.project-syndicate.org/

### ISSUE THREAD

**Issue by trevinov** [ZachSaucier/Just-Read#413]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey trevinov. 

The main reason why the content does show up is because all of their content has a class of `article__body--commentary`. This gets caught by Just Read's filter: `[class *= "comment"]`. You can add this to your custom stylesheet to work around the issue:

```
.article__body.article__body--commentary {
    display: block;
}
```

I'm unlikely to add something like this to the default CSS file so I'm going to close this issue.
