### ISSUE TITLE
cannot load images because "blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

### ISSUE THREAD

**Issue by lef-est** [ZachSaucier/Just-Read#417]
**Describe the bug**
A lot of images are broken. 
![image](https://user-images.githubusercontent.com/9643637/222892335-0a45df69-14ff-4543-805b-b1f61424a860.png)

Example console error message:
> Access to image at 'https://mmbiz.qpic.cn/mmbiz_png/Eib3tQvvNGNk3oibP0wBSbhBQzm3QyIkHP7BV8biaR7aKwyPr6VT4Az2gLf9HMU0QGuKKOQUozybC0BtyGibFflf8g/640?wx_fmt=png' from origin 'https://lib.hytc.edu.cn' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

In another similar extension (SimpRead), the pictures show up just fine.

**To Reproduce**
1. Go to https://lib.hytc.edu.cn/info/1139/16362.htm
2. Enable JustRead
3. Enjoy the broken images.

**Please complete the following information:**
 - Browser: Chrome 110.0.5481.178

**Comment by ZachSaucier** [comment]
Hey lef-est and thanks for posting. Unfortunately due to the nature of the approach of Just Read, this is unavoidable. If Just Read's approach changed, say [to use the shadow DOM instead](https://github.com/ZachSaucier/Just-Read/issues/282), then I wouldn't think this would be an issue. But there are other issues with the shadow DOM approach. As such, I am closing this as a won't-fix issue at least for the time being.
