### ISSUE TITLE
icon menu ‘slecet content to read’ lost in ver5.3.1

### ISSUE THREAD

**Issue by pinocc01** [ZachSaucier/Just-Read#426]
> Thanks for wanting to help improve Just Read! 
> 
> Please look through [the frequently asked questions](https://github.com/ZachSaucier/Just-Read#faq) and [the existing issues](https://github.com/ZachSaucier/Just-Read/issues?utf8=%E2%9C%93&q=is%3Aissue+) to make sure you're not asking what has already been discussed elsewhere.
> 
> Please delete this text from your post before posting.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Please complete the following information:**

**Additional context**

**Comment by ZachSaucier** [comment]
Hey pinocc01, thanks for the report! Sorry for the issue. 

This was due to upgrading manifests to v3 and forgetting to change `browser_action` to `action` for this entry. It should be fixed in JR version 5.3.3, which should get to your browser in a few hours once it gets through the review process.
