### ISSUE TITLE
Coding section not support

### ISSUE THREAD

**Issue by Hamidkulachi** [ZachSaucier/Just-Read#427]
i am using the just reader extension to read the tutuorial from https://dotnettutorials.net/ on this website the coding section is is very beatifull but when i enable the just reader then coding section converted into very simple text formate. so please add this feature..thanks

**Comment by ZachSaucier** [comment]
Hey Hamid and thanks for taking the time to post.

Unfortunately the way that this website does code sections is not good in terms of the markup. If you look at the actual DOM that is used (which is what Just Read uses), it treats it like a bunch of divs. If the code used "normal" code blocks (by that I mean that is used `<pre>` elements to format the code) Just Read would render it with the indentation. But in order for Just Read to support code sections on this website, you'd have to load [`EnlighterJS`](https://github.com/EnlighterJS/EnlighterJS). 

In theory one could detect if EnlighterJS is trying to be used, load the JS for it via a CDN, and render it that way. But unfortunately that would not be allowed due to restrictions that the various web stores (like Chrome's and Firefox's) have for restrictions. So you could add this ability for Just Read yourself if you wanted to but you could only use that version of Just Read for yourself.

The other alternative is that Just Read could come bundled with EnlighterJS, but given it's not very widely used and not maintained I am not willing to do that.

So this is a won't-fix. Sorry about that.
