### ISSUE TITLE
Wrong text extracted from page on defenseone.com

### ISSUE THREAD

**Issue by ljmwaugh** [ZachSaucier/Just-Read#431]
**Describe the bug**
I used Just Read on https://www.defenseone.com/ideas/2023/12/why-defense-department-attended-cop28/392924/
Instead of extracting the text for that article, it extracted the text for the next article linked at the bottom of the page.

**To Reproduce**
1. Go to ['...'](https://www.defenseone.com/ideas/2023/12/why-defense-department-attended-cop28/392924/)
2. Click on Just Read
3. See wrong text extracted

**Expected behavior**
The text from the article I was looking at extracted.

**Screenshots**
Extracted text
<img width="1511" alt="image" src="https://github.com/ZachSaucier/Just-Read/assets/23143202/d4f616ad-f5f6-48d5-88eb-d523fc0c52a1">
Expected text
<img width="1511" alt="image" src="https://github.com/ZachSaucier/Just-Read/assets/23143202/24e7c9b1-3f5b-4952-98fe-04e4bcc63c27">

**Please complete the following information:**
 - OS: Sonoma 14.2.1 (23C71)
 - Browser Chrome
 - Version Version 120.0.6099.199 (Official Build) (arm64)

**Additional context**

**Comment by ZachSaucier** [comment]
Hey ljmwaugh and thanks for taking the time to post!

This is a known issue that is discussed in more detail in #331. 

I recommend using Just Read's user selection mode in cases where Just Read's automatic selection fails. You can do so by right clicking the Just Read icon, clicking "Select content to read", hovering over the webpage, and then clicking when the content that you want to read has a blue background. I find it best to click in the white space between paragraphs so that it selects the whole article container.

I'm open to changing the automatic selection algorithm if anyone has ideas!

**Comment by ZachSaucier** [comment]
I'm going to go ahead and close this as a duplicate.
