### ISSUE TITLE
Just Read fails to open due to invalid HTML attribute

### ISSUE THREAD

**Issue by jensolafkoch** [ZachSaucier/Just-Read#433]
**Describe the bug**
A couple of days ago JustRead began to show weird effects on German newspaper site https://www.spiegel.de.

It does not load the reduced/purified version but gets stuck on a weirdly changed version of the original page. (Not all pages, but I couldn't find the difference yet.) Also the resulting pages are inconsistent: Sometimes just the scrollbar is missing, sometimes the page is completely empty, sometimes only some elements get blocked. 

But it is always an altered version of the original page, the JustRead oberlay does not show.

This problem is independent of the used Just Read CSS template. 

It occurs on latest Firefox and Chrome on Windows 11.

**To Reproduce**
1. Go to[ https://www.spiegel.de/kultur/tv/gangster-serie-crooks-auf-netflix-mit-frederick-lau-belmondo-mit-schmaeh-a-def5d211-addc-4082-b439-74eb4224cdf8?giftToken=bfd96d6a-2b01-413d-915f-d03497e53d50]( https://www.spiegel.de/kultur/tv/gangster-serie-crooks-auf-netflix-mit-frederick-lau-belmondo-mit-schmaeh-a-def5d211-addc-4082-b439-74eb4224cdf8?giftToken=bfd96d6a-2b01-413d-915f-d03497e53d50). This is a so-called gift link for articles otherwise behind a paywall. Can be opened free only 10 times. Here is another link https://www.spiegel.de/wirtschaft/unternehmen/elektro-mobilitaet-schwaeche-beim-absatz-tesla-schwaechelt-in-deutschland-besonders-a-7ba74e69-685a-426c-99db-809a435e4db4 - this is a completely free example.
2. Start Just Read, I believe the problem is related to the first image of the main article. 
4. If you remove the DOM node for the <picture> tag of the first editorial photo it does work.

**Expected behavior**
JustRead opening the olrint version as usual.

**Please complete the following information:**
 - Windows 11
 - Firefox latest 125.0b8, 
 - Chrome latest 123.0.6312.106

**Screenshots**
Before/after: After starting JustRead for the page, instead of showing the purified version, it shows the original page, just without the scrollbar.

![01](https://github.com/ZachSaucier/Just-Read/assets/47628003/2e97808d-31d3-4267-9aaa-277fc1159c5c)
![02 - no scrollbar](https://github.com/ZachSaucier/Just-Read/assets/47628003/729ba9d5-b379-4b30-b310-2552a5760369)

With editorial photo removed from DOM before/after: does work

![03 - photo deleted](https://github.com/ZachSaucier/Just-Read/assets/47628003/a637d106-7687-4451-9019-1c21bb965dc9)
![04 - does work](https://github.com/ZachSaucier/Just-Read/assets/47628003/6309982e-e65d-48de-9923-7ff6ab39fcfe)

*

I really hope there is a solution. SPIEGEL is my main source of information and I print pages really often, with a stripped down text version. Saves lot of toner and paper ... :-) Thank you!

**Comment by ZachSaucier** [comment]
Hey Jens, thanks for posting! 

I recently updated Just Read to use [Readability.js](https://github.com/mozilla/readability) from Mozilla, which is what Firefox uses in its reader view, for Just Read's auto-selection because it [outperformed](https://github.com/ZachSaucier/Just-Read/issues/331#issuecomment-2028096822) the very simple auto-selection algorithm that I came up with for Just Read.

From what I can tell, it looks like at least some of this website is rendered using Vue.js and it uses an HTML attribute of `@click`, which is not a valid HTML attribute and breaks Readability.js. 

I went ahead and [raised an issue](https://github.com/mozilla/readability/issues/859) with Readability.js. If they are responsive I am betting it will get fixed pretty quickly because I think it's a pretty simple fix. 

I can also catch this error and fall back to the old method of auto-selection in Just Read. I didn't do that originally because I assumed that Readability.js would never error like this (it never did in my tests). I'll get that updated tonight (probably ~12 hours from now).

The changes to the original page are expected -- Readability.js and Just Read remove things from the original page for performance reasons. If Just Read fails to load then the original page ends up in a broken state.

**Comment by jensolafkoch** [comment]
Hi Zach,

great + thanks for letting me know! Will check during the next couple of days after your update!

Best, Jens

**Comment by ZachSaucier** [comment]
I just pushed version 6.0.1 to the webstores which should handle this situation and work on sites like these. It will take some time to reach your devices. Let me know when you get it to confirm it works for you!

**Comment by ZachSaucier** [comment]
It looks like the submission in Chrome failed so I re-submitted now. It should work in Firefox now but in Chrome it will take a few more hours.

**Comment by jensolafkoch** [comment]
Thanks a lot! Firefox does work again (6.0.3) ... :-)
