### ISSUE TITLE
Option to change hotkey

### ISSUE THREAD

**Issue by haruska** [ZachSaucier/Just-Read#44]
Great plugin! It would be nice if we could change the hotkey from "Ctl-Shift-L" to anything (say "`")

**Comment by ZachSaucier** [comment]
This is already possible by going to `chrome://extensions/`. 

The only shortcut that you currently can't change that way is the option to start deletion mode, since it is checked through JavaScript and not Chrome itself. With that being said, users can enable a [button for deletion mode](https://github.com/ZachSaucier/Just-Read#deletion-mode) in Just Read's options, so I don't think it's a big deal that it's not very changable. Let me know if you don't agree :)

**Comment by politicus** [comment]
Hi, @ZachSaucier I just discovered your great extension. Thanks for all the time you have put in! 

As a keyboard shortcuts freak, the first thing I checked after installing the extension was if there was a conflict with a keyboard shortcut I previously set on my MacBook. 

Unfortunately, there are two as I already used the ctrl-shift-l and the ctrl-shift-k keyboard shortcuts for another application (Alfred for Mac).

I tried to modify them following your instructions in the previous comment but the google chrome version I use (Version 66.0.3359.139) didn't let me modify these keyboard shortcuts as I couldn't find the little box we used to have in previous google chrome versions.

**Comment by ZachSaucier** [comment]
@politicus Thanks for the report! I hadn't tried changing hotkeys since Chrome's recent update of the extensions page. Changing your shortcuts can now be found at `chrome://extensions/shortcuts`. It's accessible via the hamburger icon in the top left of the `chrome://extensions/` page if you want to use their UI to navigate to it.

**Comment by politicus** [comment]
Didn't know this page existed. Thanks for the tip!
