### ISSUE TITLE
Selecting meta information based on particular selectors

### ISSUE THREAD

**Issue by ghost** [ZachSaucier/Just-Read#45]
Hey, thank you for your great, great tool. I use it a lot for reading!

Especially on Wikipedia, which is why I thought of a suggestion. Now, on \*.wikipedia.org/\* the date and author are not set:

![image](https://cloud.githubusercontent.com/assets/7526559/22880105/31269278-f1e1-11e6-90cc-6b8e92fb1262.png)

However, reviewing the source learns that the date is set in ID `footer-info-lastmod`:

![image](https://cloud.githubusercontent.com/assets/7526559/22879978/aa8f7298-f1e0-11e6-898e-ecd86195b50a.png)

And the author is of course `Wikipedia`, but could be read from ID `siteSub` too, so it would be translated on Wikipedia sites in other languages:
![image](https://cloud.githubusercontent.com/assets/7526559/22880034/dbff0910-f1e0-11e6-85ce-0c8bada9682c.png)

I could try to find a way in JS to get those values from those ID's, if you would like. Or is there another solution?

**Comment by ZachSaucier** [comment]
Searching for specific IDs on a site-by-site basis in order to find meta information like date and author (or page content for that matter) would lead to a crap ton of selector searching every time Just Read is ran. As such, I won't be implementing any such selector searching other than what I currently have (or something similar) which checks for things called "author", "date", etc. If a site doesn't use something reasonable then Just Read won't be able to find it. The only real way to do this would be to use some AI and parse all the text on a page to try and determine it, which is a bit out of scope for Just Read at least at this point in time.

You can always edit this information yourself by hovering over it and clicking the pencil that appears. You could also write a userscript to automatically change this information on Wikipedia if you read those pages regularly.

P.S. Your theme looks great! You should share it with people on the [theme sharing post](https://github.com/ZachSaucier/Just-Read/issues/4).

**Comment by fcturner** [comment]
Right, thanks :+1: 

I altered your JS to add 10 lines of code. Now, Wikipedia looks great. There's one thing I think you *should*  change. But I'll put it in a Pull Request.

Thanks for the great extension!

**Comment by fcturner** [comment]
I **do** like an option in the settings where one can set an ID or class for a date, author or title per web address :smile: :smile: 

See this as an extension on your extension then :wink:

**Comment by ZachSaucier** [comment]
That's not a terrible idea. I'll add it to my list of things to investigate more deeply

**Comment by fcturner** [comment]
Thanks. Wikipedia is still [the 6th website in the global Alexa Top 500](http://www.alexa.com/topsites) and solely used for article reading, so I think it couldn't hurt add some code to optimize the view of the most visited article website ever. But user options that allow such would be great too :+1:

**Comment by ZachSaucier** [comment]
This is now supported in the premium version of Just Read! See [this post](https://github.com/ZachSaucier/Just-Read/#q-can-i-customize-which-selectors-just-read-uses-for-selecting-the-date-author-title-header-image-and-content) for more information.
