### ISSUE TITLE
Incomplete rendering and printing cut off

### ISSUE THREAD

**Issue by laflier** [ZachSaucier/Just-Read#51]
Using Just-Read in Chrome 56.0.2924.87 in OSX 10.11.6, on an encyclopedia article at https://plato.stanford.edu/entries/faith/, I encounter the following issues:

1. Automatic selection leaves off the TOC and the introduction above it, and also the bibliography. Both are important to researchers! I initially thought this might be correctable through CSS, but it appears to be a JS issue.

2. Manual selection is a workaround for the auto-select problem, but when I attempt to print the manually-selected selection (using the Just-Read print button) many pages are dropped from the bottom of the article, similar to what was reported by kiizu.

**Comment by ZachSaucier** [comment]
Hello and thanks for the issue report! Sorry you're facing an issue.

The first issue is the same as #32. I've added the problematic page you linked to a [running list of problematic sites](https://github.com/ZachSaucier/Just-Read/issues/32#issuecomment-275704529).

As for the second issue, you're right that many pages are cut off, even for me (unlike the other bug report). The print issue was larger than I originally assumed. I'll look into it ASAP, but might not get to it in the upcoming week due to other work I have outside of Just Read.

**Comment by ZachSaucier** [comment]
I was able to fix this by applying `@media screen { }` around the `* { box-sizing: border-box; }` CSS in the default stylesheet. It seems to be a bug in Chrome itself, but I'm working on recreating the issue to report it. This should be fixed as of Just Read version 1.0.22, so make sure your version updates or apply the changes yourself!

**Comment by jessica-cobb** [comment]
I was also having the same printing problem. I tried adding the media-print line and it did nothing. After reading that the issue might be with Chrome's print function, I found a workaround is to change the margins away from "default" to "none" or "custom" appears to bring back the missing text.
