### ISSUE TITLE
content not detected:  slashdot.org

### ISSUE THREAD

**Issue by MichaelJCole** [ZachSaucier/Just-Read#53]
Hi, just a friendly note I'm excited to use your plugin on slashdot.org, but it didn't detect the content.

**Comment by ZachSaucier** [comment]
Just Read isn't really meant to render pages like the "articles" on slashdot, given they are more like summaries or excerpts than real articles. Are you expecting only the article section to be shown when Just Read is ran?

I may make an exception and implement a check for slashdot itself since it's fairly commonly used and I can see a way to do so.

**Comment by MichaelJCole** [comment]
Hey Zach, when I tried it, I was expecting it to show the article summaries in a list, with links to the individual articles.

If I could browse the web Just Read on by default that would be amazing - like AdBlock.  I saw in another post you were talking about a premium version.  So tired of reading an article and 5s later having to click a popup out of my face.

If there was a version that crowdsourced pulling out just the content, so most of the websites I visited were Just Readible, I'd gladly pay for that.  You could offer some free subscription time to contributors.

**Comment by ZachSaucier** [comment]
Ah, so you were talking about the homepage that has the list of articles, not even one of the individual summary page. In that case, you could use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the container of all the summaries to make them show.

Just Read does [have an auto-enable functionality](https://github.com/ZachSaucier/Just-Read#auto-enable-just-read-on-specific-websites) you could use for most sites that you read.

As for having a version that turned *every webpage* into a Just Read format, that's not really feasible (at least as far as I know of). There are so many variations of layout, often times with horrid markup not meeting standards, so finding what is truly the content and what is the fluff is difficult to do generically. That's why Just Read focuses on article-type pages.

**Comment by MichaelJCole** [comment]
Hey Zach, I haven't tried it, but there is a "Reader View" feature in Firefox that does something similar.  It removes ads, so it will never be a feature in Google Chrome.  Might be worth checking how they do it and/or partnering with them depending your vision for your project.  That was why I started searching for an extension like Just Read.  In conclusion, thanks for the extension!

**Comment by MichaelJCole** [comment]
https://support.mozilla.org/t5/Basic-Browsing/Firefox-Reader-View-for-clutter-free-web-pages/ta-p/38466

**Comment by ZachSaucier** [comment]
I'm familiar with it and Safari's, though I'm not an very active user of either (for obvious reasons). 

Keep in mind that they've been creating that with a team for years and I'm doing this for free in my spare time for that past year :)

**Comment by ZachSaucier** [comment]
Firefox's reader mode isn't available on slashdot.org. Due to the nature of the site (a list of articles, not articles themselves), I'm going to close this issue as a "wont-fix" because Just Read isn't meant to read these types of pages.
