### ISSUE TITLE
Content Not Detected - searchengineland.com

### ISSUE THREAD

**Issue by weaverhe** [ZachSaucier/Just-Read#59]
I tried to read a few articles on the searchengineland site, but none of them picked up the content properly, just the title.

Example - http://searchengineland.com/technical-argument-quality-content-270556

![screen shot 2017-03-15 at 9 38 12 am](https://cloud.githubusercontent.com/assets/6454985/23953628/2c5a606e-0963-11e7-9fb2-f591a50b1a13.png)

**Comment by ZachSaucier** [comment]
Thanks for the report! This is due to the websites curious use of a class called `sharing_controls_startpoint_fixed` on the main content container. Since Just Read tries to hide all "sharing" elements, this content is hidden. 

I'll look into how to not hide these types of elements if it is the top most container.

**Comment by ZachSaucier** [comment]
This should be fixed as of Just Read version 1.0.24. The change should be propagating to the Chrome store now.

I implemented a check to make sure any top-level elements are displayed (which may cause problems if things Just Read *actually* wants to hide are on the top level, but that isn't the case in any of the sites in my test list and seems like a fair trade off).
