### ISSUE TITLE
Guardian page shows huge graphics and no date

### ISSUE THREAD

**Issue by jefro108** [ZachSaucier/Just-Read#60]
When I go to https://www.theguardian.com/us-news/2017/mar/22/rex-tillerson-i-didnt-want-this-job and try to read it I get a huge graphic at the beginning and no date.

See
<img width="629" alt="screen shot 2017-03-22 at 10 37 48" src="https://cloud.githubusercontent.com/assets/12976435/24193900/c78e79ca-0eeb-11e7-8dd0-abdbe7667daa.png">

as compared with the original

<img width="1390" alt="screen shot 2017-03-22 at 10 38 10" src="https://cloud.githubusercontent.com/assets/12976435/24193911/d69b28a0-0eeb-11e7-9ee6-f5392880a2fe.png">

It appears to be taking a graphic that's used for navigating pictures incorrectly!

**Comment by ZachSaucier** [comment]
Thanks for the report! Images like this are difficult to catch generically, but it seems like adding another rule to handle elements that use "icon" in their class would work for this page and similar pages. I'll add something like `[class *= "icon"] { max-width: 1em; }` to make sure they don't get too big. Hopefully it won't cause too many other problems :P 

As for the date, *I* can't even find what the date of the article is supposed to be, let alone finding it in their poor markup. So that likely won't be fixed for a page like this. Keep in mind that you can edit the meta information like the date yourself by hovering over it and clicking the pencil icon if you need it there for printing or something like that.

**Comment by jefro108** [comment]
That's great you can sort it easily. 

The date is actually visible to the left of the main picture for the article in the second screenshot above - it has a class of content__dateline in the html but there's also a meta property listed:

<meta property="article:published_time" content="2017-03-21T06:30:06.000Z"/>

Would that be information you could use to include it in Just-Read?

**Comment by ZachSaucier** [comment]
Thanks for pointing it out to me. I looked back at the date selection function I wrote (over a year ago at this point) and have now revised it so its selection is a little bit smarter and more developer-efficient. So date selection now works on the page you linked, but there are still many cases where it does not because of how poor most site's markup is, especially regarding dates.

I'm pushing the changes for both bugs now.

**Comment by jefro108** [comment]
Cool that it's updated so quickly!

Just wondering why you've given [class *= "icon"] { max-width: 1em; }  rather than max-width of zero?

**Comment by ZachSaucier** [comment]
Because potentially there could be good use of an icon element. Of course you're always welcome to edit your stylesheet to remove it completely. If you do that, you might want to use `display: none;` instead.

**Comment by jefro108** [comment]
Ok fine. That proved easier than I thought it would. Thanks :)
