### ISSUE TITLE
Content Not Detected - db.bme.hu

### ISSUE THREAD

**Issue by octolith** [ZachSaucier/Just-Read#62]
I tried to read the help manual for one of my classes at the university. However content is not picked up properly, only the title.

Example - [https://www.db.bme.hu/tartalom/hallgatoi-utmutato-jdbc-mereshez](https://www.db.bme.hu/tartalom/hallgatoi-utmutato-jdbc-mereshez)

![image](https://cloud.githubusercontent.com/assets/4784873/24294378/81485b00-1096-11e7-8c78-c5bbca067537.png)

**Comment by ZachSaucier** [comment]
Hello and thanks for the report! This seems to be due to an over-eager hiding of content presumed to be superfluous due to a selector `[class *= "hidden"] { display: none; }` and the site's use of `.field-label-hidden` on the article content.

I'll change the selector to the less general `.hidden { display: none; }` which will fix the problem, but potentially some other selectors using a class like `.visually-hidden` won't be (which is sad, but a fair trade off I suppose).

**Comment by ZachSaucier** [comment]
I went ahead and pushed the changes to the Chrome store because I also fixed another more important bug. So this should be fixed as of 1.0.26
