### ISSUE TITLE
text has black box around it and is not correct width

### ISSUE THREAD

**Issue by veddit** [ZachSaucier/Just-Read#64]
When reading this page, Just Read adds a box around the text and makes the line length smaller than how it appears on all the other pages I read.
https://www.interaction-design.org/literature/article/service-design-design-is-not-just-for-products

It looks like:
![image](https://cloud.githubusercontent.com/assets/604782/24399569/194e674e-13a5-11e7-90a2-5cce9ee717af.png)

vs normally looking like:
![image](https://cloud.githubusercontent.com/assets/604782/24399588/2c94d022-13a5-11e7-83dd-102e65a7f70a.png)
(https://www.interaction-design.org/literature/topics/service-design)

**Comment by ZachSaucier** [comment]
This is because the site uses a class `.ux-article-content-with-sidebar__content` and Just Read selects all elements with `sidebar` in the class and formats them with a slightly smaller width and border. 

While this is technically a bug, there's no good way to fix it without removing the functionality of showing sidebar content styled a little different. Since this is a rare exception and ultimately not much of a bug, I won't implement any change.

If you really need to have it styled like everything else for some reason, you could remove  the `[class *= "sidebar"]` selector in your stylesheet, or write a rule to override elements with the class sidebar who are direct children of `.content-container`.
