### ISSUE TITLE
Heading is Missing

### ISSUE THREAD

**Issue by IDNIndia** [ZachSaucier/Just-Read#69]
The heading is Missing for this URL:

http://timesofindia.indiatimes.com/city/mumbai/china-min-india-hasnapost-confirmed-itaposs-participation-in-bri-forum/articleshow/58316660.cms

**Comment by ZachSaucier** [comment]
Thanks for the report. But there are some cases where Just Read simply makes a mistake. Mistakes are guaranteed to happen for some sites because most sites have terrible markup. I appreciate your willingness to report bugs, but I cannot fix every little error. Please refrain from making a GitHub issue unless you're unable to get the resulting format that you really need.

In this case, you can use Just Read's info correction to manually fix the title if you need it to be correct. I'm marking this as a wont-fix because it is a very minor error that can be worked around using tools built into Just Read.

**Comment by IDNIndia** [comment]
Maxthon 5 browser's inbuilt reader mode is able to render the page without
any issue, hence I thought this could be a bug or a coding issue.

Anyways, point taken.

Regards,
JB

**Comment by ZachSaucier** [comment]
I understand, and there's work to be done to improve Just Read, but a new issue for every little thing would be in the hundreds already :P 

If you'd like to contribute and squash some bugs feel free!
