### ISSUE TITLE
Incorrect author chosen on Politico.com

### ISSUE THREAD

**Issue by upekshapriya** [ZachSaucier/Just-Read#75]
An author from a connected article listed at the bottom of the page is chosen as the author rather than the correct one! 

http://www.politico.com/magazine/story/2017/06/02/most-interesting-man-world-friends-barack-obama-215215

Jack Shafer is listed (who appears in a rel="author" tag within a link) rather than the correct author Jonathan Goldsmith who appears within  a itemprop="author" tag.

**Comment by ZachSaucier** [comment]
Thanks a lot for the report! I'll get around to fixing that as soon as I can find time.

**Comment by ZachSaucier** [comment]
I don't have any ideas about how to fix this error without using some type of wider page analysis (probably using a form of machine learning). Since that's a bit far out of scope of Just Read's purposes, this error is a "wont-fix".

Keep in mind that you can manually edit any incorrect meta info by hovering it and clicking the pencil icon!
