### ISSUE TITLE
Page not rendering on Vice

### ISSUE THREAD

**Issue by annaj** [ZachSaucier/Just-Read#77]
https://www.vice.com/en_ca/article/how-to-date-a-woman-with-adhd

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.

**Comment by DoctorOgg** [comment]
might want to re-examine vise,https://www.vice.com/en_us/article/5dm3vx/technology-has-made-us-labor-law-obsolete-experts-say shows only the page title

**Comment by ZachSaucier** [comment]
Hey @DoctorOgg. The selection is actually working on the page that you link to. The article content is just being hidden because Just Read tries to hide irrelevant content like forms. That site uses a class of `short-form-v2__heading` etc. which is hidden by Just Read's rule of `[class *= "-form-"]`. 

You can work around this by adding `[class *= 'short-form'] { display: block; }` to your stylesheet.

**Comment by DoctorOgg** [comment]
yah, that fixed the bug, hopefully, a longterm fix can make it into the product so most users don't have to patch the style sheet...

**Comment by ZachSaucier** [comment]
Another alternative is to not alter your stylesheet but use Just Read's [user selection mode](https://github.com/ZachSaucier/Just-Read#user-selection-mode) to select the content. User selection mode is meant for cases where Just Read fails to select the content like this.
