### ISSUE TITLE
Highlighter functionality

### ISSUE THREAD

**Issue by JACKCHEN99** [ZachSaucier/Just-Read#8]
I like Just Read. It would be better if it had a highlighter function, such as the one in "Super Simple Highlighter". We use that extension to mark the text when reading, but it doesn't work when using Just Read's read mode.

**Comment by ZachSaucier** [comment]
Hello Jack and thanks for the suggestion! 

I have no intention of adding this type of functionality because it goes outside of the minimal scope of just reading articles in a custom format that is the intention of the extension. The read mode for Just Read is an iframe, which can likely be selected from another extension (like Super Simple Highlighter), so you might post on their support page asking them to also allow iframes to be highlighted.

With that being said, I'm open to adding a feature like this given a high volume of users request it.

**Comment by ZachSaucier** [comment]
After thinking about this some more, I've decided to start work on a paid version of Just Read. See #20 for more details

**Comment by ZachSaucier** [comment]
This is now available in the premium version of Just Read. See [this post](https://github.com/ZachSaucier/Just-Read/#q-how-can-i-add-annotations-and-comments) for instructions and [Just Read's homepage](https://justread.link/) for more info on the premium version.
