### ISSUE TITLE
Site shows blank screen when in Auto-run list

### ISSUE THREAD

**Issue by drewski3420** [ZachSaucier/Just-Read#86]
When I add washingtonpost.com to the Auto-run domain list, the article initially displays as normal in Just Read. However, after a few seconds (and the page refresh icon continues to spin), the page just displays as completely blank.

If I remove the domain from auto run and trigger just read as normal, it works fine.

**Comment by ZachSaucier** [comment]
Very interesting. the Washington Post must be doing something weird on their side. I'll look into it when I have more time.

**Comment by ZachSaucier** [comment]
This seems to have been fixed on the Washington post site either due to an update of Just Read or the Washington post. I tested on [this article](https://www.washingtonpost.com/politics/trump-to-hold-major-briefing-on-opiod-crisis/2017/08/08/8b7cd146-7c2f-11e7-9d08-b79f191668ed_story.html). 

@drewski3420  can you confirm?

**Comment by ZachSaucier** [comment]
This should be fixed as of Just Read version 1.1.15
