### ISSUE TITLE
Single paragraph article not being selected

### ISSUE THREAD

**Issue by barcel0** [ZachSaucier/Just-Read#87]
Trying to discretely read Oracle's java documentation at work but apparently its rendering the footer content instead of the main one!

https://docs.oracle.com/javase/tutorial/java/nutsandbolts/flow.html

**Comment by ZachSaucier** [comment]
This is because it only has 1 paragraph on that page. Just Read [works on other pages](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/operators.html) just fine. 

You can work around this by using Just Read's user selection mode. I'll keep this in mind when redesigning JR's auto-selection.

**Comment by barcel0** [comment]
Great, thanks! Didn't know about that feature, I'll use it next time!

**Comment by ZachSaucier** [comment]
This should be more or less fixed in the latest version (1.2.0) with Just Read's new auto-selection algorithm.

**Comment by barcel0** [comment]
Many thanks Zach. Will have a look to it next week!
