### ISSUE TITLE
Formatter doesn't respect the <pre> tag

### ISSUE THREAD

**Issue by ivannieto** [ZachSaucier/Just-Read#9]
This comes when reading articles with embedded code blocks inside a pre tag. It doesn't respect the embedded code and uses it as normal text. 

Could be a way to make an exception for this behaviour? 

I love the way Just Read formats websites. It's quite useful to download pdf articles for later-reading. 

This feature will improve it for sure.

Example of the current behaviour:

When some piece of code like:

<pre>leer_teclado_asincrono(t =&gt; {
  leer_fichero_asincrono(f =&gt; {
    leer_datos_asincrono(d =&gt; {
      imprime(t,f,d)
    })
  })
})</pre>

It's shown as a simple line when Just Read is ON:

leer_teclado_asincrono(t => { leer_fichero_asincrono(f => { leer_datos_asincrono(d => { imprime(t,f,d) }) }) })

**Comment by ivannieto** [comment]
Hmmm I see now, the article has no code tag embedded into the pre content so it should had bypassed it. BTW, text inside a pre tag should be formatted as it is stated. It's not relative to the code tag (if we want to avoid this kind of problems). You could extract the code from this article: [http://elmanantialdebits.blogspot.com.es/2013/08/que-es-eso-de-la-programacion-asincrona.html](url)

**Comment by ZachSaucier** [comment]
Thanks for bringing this up. This behavior was purposely implemented. `<pre>` tags with no `<code>` inside of them are converted to `<p>` tags in Just Read's format.

This is done because some sites that I've come across (unfortunately I didn't save the link(s)) put regular types of text content inside of the `<pre>` tag. Since Just Read is meant to take all formatting away from article type of content, I convert it to a `<p>` tag so that the browser's styling is removed.

With that being said, if you come across several sites where this is an issue, where the `<pre>` formatting is actually needed, I'm open to changing the way the `<pre>`s are handled.

**Comment by ZachSaucier** [comment]
The error in handling line breaks inside of `<pre>`s has been fixed in 51df38a / version 1.0.2

**Comment by ZachSaucier** [comment]
Update: The error in handling line breaks inside of `<pre>`s should be fixed as of b2c7227 / version 1.0.2. Let me know if that is satisfactory for your use case.

**Comment by ivannieto** [comment]
Line breaks work well now for the example provided, but it keeps by passing indenting.

With Just Read ON it shows this now, as you can see:

leer_teclado_asincrono(t => {
leer_fichero_asincrono(f => {
leer_datos_asincrono(d => {
imprime(t,f,d)
})
})
})

**Comment by ZachSaucier** [comment]
For now I will keep the functionality as it was originally designed for the reasons stated above. 

If you're writing pages that use code, make sure to use the `<code>` element!

**Comment by ivannieto** [comment]
I always do it. The example provided is not written by me, it was just found on the net. :smile: Cool. I'll be waiting for updates. Thanks, and thanks for the great job Zach!

**Comment by ZachSaucier** [comment]
Just a note: if there's a section of code that is only inside of a `<pre>` tag that you *really* need to be formatted, you can use your dev tools to add the `<code>` tag surrounding that content **before** running Just Read. Since it runs on the page at the time when it's ran, Just Read will include the `<code>` in its version.

**Comment by dflock** [comment]
This breaks code blocks in any site that uses MediaWiki - like Wikipedia, etc... See this page for an example: https://en.wikipedia.org/wiki/Web_storage#sessionStorage

The code blocks on Wikipedia are just `<pre>` tags, not `<pre><code>`, so they get borked.

Would be nice if there was a setting for this - "Keep <pre> tags" or something.

**Comment by ZachSaucier** [comment]
I added the ability for users to choose whether or not to reformat `<pre>` tags in "Additional options" on the Options page as of version 1.0.14.

Thanks for the comment!

**Comment by dflock** [comment]
Great, thanks!
